from django.test import TestCase

from django.conf import settings

import datetime

from .ssh_command import ssh_command, save_file_with_contents

# Create your tests here.

# These tests require ssh be setup with keys
class SSHCommandTest(TestCase):
	def test_ls(self):
		ssh_command(settings.COMMAND_HOST, "ls", False, False)
		
	def test_save_simple_file(self):
		contents = 'This is a file generated by the test suite at {}.'.format(datetime.datetime.now())
		name = 'Test'
		date_string = '20180101'
		extension = 'test_extension'
		save_file_with_contents(contents, date_string, name, extension, settings.COMMAND_HOST)
