# Generated by Django 2.0.1 on 2018-03-10 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.IntegerField()),
                ('extract', models.IntegerField()),
                ('library', models.IntegerField()),
                ('experiment', models.CharField(max_length=20)),
                ('udg', models.CharField(max_length=10)),
                ('workflow', models.CharField(max_length=100)),
                ('report_path', models.CharField(blank=True, max_length=300)),
                ('capture_name', models.CharField(max_length=50)),
                ('analysis_time', models.DateTimeField(verbose_name='completed analysis time')),
            ],
        ),
        migrations.CreateModel(
            name='DemultiplexedSequencing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i5_index', models.CharField(max_length=10)),
                ('i7_index', models.CharField(max_length=10)),
                ('p5_barcode', models.CharField(blank=True, max_length=50)),
                ('p7_barcode', models.CharField(blank=True, max_length=50)),
                ('reference', models.CharField(max_length=30)),
                ('path', models.CharField(max_length=300)),
                ('analyzed_library', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sequencing_run.AnalyzedLibrary')),
            ],
        ),
        migrations.CreateModel(
            name='Flowcell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flowcell_text_id', models.CharField(max_length=20, unique=True, verbose_name='flowcell')),
                ('sequencing_date', models.DateField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SequencingAnalysisRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='sequencing run name')),
                ('start', models.DateTimeField(verbose_name='sequencing run processing run start time')),
                ('processing_state', models.IntegerField(choices=[(0, 'started'), (100, 'copying sequencing data to Orchestra/O2'), (200, 'preparing json inputs'), (300, 'preparing run script'), (400, 'demultiplexing and aligning'), (500, 'running analysis'), (1000, 'finished'), (-1, 'failed')], default=0)),
                ('sequencing_date', models.DateField()),
                ('slurm_job_number', models.IntegerField(null=True)),
                ('top_samples_to_demultiplex', models.IntegerField()),
                ('prior_flowcells_for_analysis', models.ManyToManyField(to='sequencing_run.Flowcell')),
            ],
        ),
        migrations.CreateModel(
            name='SequencingRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illumina_directory', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='sequencinganalysisrun',
            name='sequencing_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequencing_run.SequencingRun'),
        ),
        migrations.AddField(
            model_name='sequencinganalysisrun',
            name='triggering_flowcell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_analysis', to='sequencing_run.Flowcell'),
        ),
        migrations.AddField(
            model_name='demultiplexedsequencing',
            name='flowcell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequencing_run.Flowcell'),
        ),
        migrations.AlterUniqueTogether(
            name='demultiplexedsequencing',
            unique_together={('flowcell', 'p5_barcode', 'p7_barcode', 'i5_index', 'i7_index', 'reference')},
        ),
    ]
