# Generated by Django 2.0.1 on 2018-03-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequencing_run', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequencingRunID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='flowcell',
            name='name',
        ),
        migrations.AlterField(
            model_name='sequencinganalysisrun',
            name='processing_state',
            field=models.IntegerField(choices=[(0, 'started'), (100, 'copying sequencing data to Orchestra/O2'), (200, 'preparing json inputs'), (300, 'preparing run script'), (400, 'demultiplexing and aligning'), (500, 'running analysis'), (600, 'running analysis, preliminary report ready'), (1000, 'finished'), (-1, 'failed')], default=0),
        ),
    ]
