# Generated by Django 2.0.3 on 2018-04-03 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequencing_run', '0002_auto_20180330_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedSequencingRunID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_order', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequencing_run.SequencingRunID')),
                ('sequencing_analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequencing_run.SequencingAnalysisRun')),
            ],
            options={
                'ordering': ['interface_order'],
            },
        ),
        migrations.AddField(
            model_name='sequencinganalysisrun',
            name='sample_set_names',
            field=models.ManyToManyField(through='sequencing_run.OrderedSequencingRunID', to='sequencing_run.SequencingRunID'),
        ),
        migrations.AlterUniqueTogether(
            name='orderedsequencingrunid',
            unique_together={('sequencing_analysis_run', 'interface_order')},
        ),
    ]
