# Generated by Django 2.1.2 on 2018-10-18 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequencing_run', '0004_auto_20180403_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PositiveControlLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment', models.CharField(max_length=20)),
                ('udg', models.CharField(max_length=10)),
                ('workflow', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=30)),
                ('path', models.CharField(max_length=300)),
                ('release_time', models.DateTimeField(auto_now_add=True, verbose_name='release time')),
                ('version', models.IntegerField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sequencing_run.Batch')),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sequencing_run.Capture')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sequencing_run.SequencingRunID')),
            ],
        ),
        migrations.CreateModel(
            name='ReleasedLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment', models.CharField(max_length=20)),
                ('udg', models.CharField(max_length=10)),
                ('workflow', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=30)),
                ('path', models.CharField(max_length=300)),
                ('release_time', models.DateTimeField(auto_now_add=True, verbose_name='release time')),
                ('version', models.IntegerField()),
                ('sample', models.IntegerField()),
                ('sample_suffix', models.CharField(default='', max_length=5)),
                ('lysis', models.IntegerField(null=True)),
                ('extract', models.IntegerField(null=True)),
                ('library', models.IntegerField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sequencing_run.Batch')),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sequencing_run.Capture')),
            ],
        ),
        migrations.RemoveField(
            model_name='demultiplexedsequencing',
            name='analyzed_library',
        ),
        migrations.DeleteModel(
            name='AnalyzedLibrary',
        ),
        migrations.AddField(
            model_name='demultiplexedsequencing',
            name='library',
            field=models.ManyToManyField(to='sequencing_run.ReleasedLibrary'),
        ),
        migrations.AlterUniqueTogether(
            name='releasedlibrary',
            unique_together={('sample', 'sample_suffix', 'lysis', 'extract', 'library', 'experiment', 'udg', 'reference', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='positivecontrollibrary',
            unique_together={('name', 'version')},
        ),
    ]
