# Generated by Django 2.1.7 on 2019-05-01 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequencing_run', '0005_auto_20181018_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='demultiplexedsequencing',
            name='flowcells',
            field=models.ManyToManyField(related_name='source_flowcells', to='sequencing_run.Flowcell'),
        ),
        migrations.AddField(
            model_name='sequencinganalysisrun',
            name='triggering_flowcells',
            field=models.ManyToManyField(related_name='input_flowcells', to='sequencing_run.Flowcell'),
        ),
        migrations.AlterField(
            model_name='demultiplexedsequencing',
            name='flowcell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_flowcell', to='sequencing_run.Flowcell'),
        ),
    ]
