# Generated by Django 2.1.7 on 2019-05-01 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequencing_run', '0007_auto_20190501_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequencinganalysisrun',
            name='triggering_flowcell',
        ),
        migrations.AlterUniqueTogether(
            name='demultiplexedsequencing',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='demultiplexedsequencing',
            name='flowcell',
        ),
    ]
