# Generated by Django 2.1.8 on 2020-02-04 17:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
        ('sequencing_run', '0008_auto_20190501_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(max_length=20)),
                ('modification_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_by', models.CharField(max_length=20)),
                ('demultiplexing_sequences', models.BigIntegerField()),
                ('sequences_passing_filters', models.BigIntegerField(null=True)),
                ('sequences_aligning', models.BigIntegerField(null=True)),
                ('sequences_aligning_post_dedup', models.BigIntegerField(null=True)),
                ('coverage', models.FloatField(null=True)),
                ('mean_median_sequence_length', models.FloatField(null=True)),
                ('damage_last_base', models.FloatField(null=True)),
                ('consensus_match', models.FloatField(null=True)),
                ('consensus_match_95ci', models.CharField(blank=True, max_length=30)),
                ('haplogroup', models.CharField(blank=True, max_length=30)),
                ('haplogroup_confidence', models.FloatField(null=True)),
                ('track_mt_rsrs', models.CharField(blank=True, max_length=160)),
                ('report', models.CharField(blank=True, max_length=35)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.Results')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NuclearAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(max_length=20)),
                ('modification_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_by', models.CharField(max_length=20)),
                ('bioinfo_processing_protocol', models.CharField(max_length=20)),
                ('pulldown_logfile_location', models.CharField(max_length=300)),
                ('pulldown_1st_column_nickdb', models.CharField(max_length=50)),
                ('pulldown_2nd_column_nickdb_alt_sample', models.CharField(max_length=50)),
                ('pulldown_3rd_column_nickdb_bam', models.CharField(max_length=200)),
                ('pulldown_4th_column_nickdb_hetfa', models.CharField(max_length=100)),
                ('pulldown_5th_column_nickdb_readgroup_diploid_source', models.TextField()),
                ('seq_run_file_name', models.CharField(max_length=150)),
                ('track_id_report_file', models.CharField(max_length=160)),
                ('raw_reads_or_deindexing', models.BigIntegerField()),
                ('sequences_merge_pass_barcode', models.BigIntegerField(null=True)),
                ('target_sequences_pass_qc_predup', models.BigIntegerField(null=True)),
                ('target_sequences_pass_qc_postdedup', models.BigIntegerField(null=True)),
                ('unique_targets_hit', models.IntegerField(null=True)),
                ('unique_snps_hit', models.IntegerField(null=True)),
                ('coverage_targeted_positions', models.FloatField(null=True)),
                ('expected_coverage_10_marginal_uniqueness', models.FloatField(null=True)),
                ('expected_coverage_37_marginal_uniqueness', models.FloatField(null=True)),
                ('marginal_uniqueness', models.FloatField(null=True)),
                ('mean_median_seq_length', models.FloatField(null=True)),
                ('damage_last_base', models.FloatField(null=True)),
                ('x_hits', models.IntegerField(null=True)),
                ('y_hits', models.IntegerField(null=True)),
                ('sex', models.CharField(blank=True, max_length=30)),
                ('y_haplogroup', models.CharField(blank=True, max_length=80)),
                ('angsd_snps', models.IntegerField(null=True)),
                ('angsd_mean', models.FloatField(null=True)),
                ('angsd_z', models.FloatField(null=True)),
                ('assessment', models.CharField(max_length=350)),
                ('version_release', models.CharField(max_length=20)),
                ('results_note', models.TextField()),
                ('find', models.TextField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.Results')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShotgunAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(max_length=20)),
                ('modification_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_by', models.CharField(max_length=20)),
                ('bioinfo_processing_protocol', models.CharField(max_length=50)),
                ('track_id', models.CharField(max_length=150)),
                ('raw_sequences', models.BigIntegerField()),
                ('sequences_passing_filters', models.BigIntegerField(null=True)),
                ('reads_mapped_hg19', models.BigIntegerField(null=True)),
                ('mean_median_sequence_length', models.FloatField(null=True)),
                ('percent_hg19', models.FloatField(null=True)),
                ('damage_rate', models.FloatField(null=True)),
                ('fraction_hg19_hit_mtdna', models.FloatField(null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.Results')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpikeAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(max_length=20)),
                ('modification_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_by', models.CharField(max_length=20)),
                ('bioinfo_processing_protocol', models.CharField(max_length=50)),
                ('spike_track_id', models.CharField(blank=True, max_length=150)),
                ('spike_pre_aut', models.IntegerField(null=True)),
                ('spike_post_aut', models.IntegerField(null=True)),
                ('spike_post_y', models.IntegerField(null=True)),
                ('spike_complexity', models.FloatField(null=True)),
                ('spike_sex', models.CharField(blank=True, max_length=30)),
                ('screening_outcome', models.CharField(blank=True, max_length=50)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.Results')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='demultiplexedsequencing',
            name='p5_barcode',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='demultiplexedsequencing',
            name='p7_barcode',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
