# Generated by Django 3.0.4 on 2020-04-11 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
        ('sequencing_run', '0009_auto_20200331_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisfiles',
            name='bioinfo_processing_protocol',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='analysisfiles',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='samples.Results'),
        ),
        migrations.AddField(
            model_name='analysisfiles',
            name='pulldown_1st_column_nickdb',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='analysisfiles',
            name='pulldown_2nd_column_nickdb_alt_sample',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='analysisfiles',
            name='pulldown_3rd_column_nickdb_bam',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='analysisfiles',
            name='pulldown_4th_column_nickdb_hetfa',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='analysisfiles',
            name='pulldown_5th_column_nickdb_readgroup_diploid_source',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='analysisfiles',
            name='pulldown_logfile_location',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='analysisfiles',
            name='shotgun_bam',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='nuclearanalysis',
            name='damage_restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nuclearanalysis',
            name='assessment',
            field=models.TextField(),
        ),
    ]
