# Generated by Django 3.0.4 on 2020-04-11 02:52

from django.db import migrations

def move_pulldown_fields_to_analysisfiles(apps, schema_editor):
	NuclearAnalysis = apps.get_model('sequencing_run', 'NuclearAnalysis')
	AnalysisFiles = apps.get_model('sequencing_run', 'AnalysisFiles')
	
	# move the pulldown fields from NuclearAnalysis to AnalysisFiles
	for nuclear in NuclearAnalysis.objects.all():
		analysis_files, created = AnalysisFiles.objects.get_or_create(parent__exact=nuclear.parent)
		analysis_files.parent = nuclear.parent
		analysis_files.bioinfo_processing_protocol = nuclear.bioinfo_processing_protocol
		analysis_files.pulldown_logfile_location = nuclear.pulldown_logfile_location
		analysis_files.pulldown_1st_column_nickdb = nuclear.pulldown_1st_column_nickdb
		analysis_files.pulldown_2nd_column_nickdb_alt_sample = nuclear.pulldown_2nd_column_nickdb_alt_sample
		analysis_files.pulldown_3rd_column_nickdb_bam = nuclear.pulldown_3rd_column_nickdb_bam
		analysis_files.pulldown_4th_column_nickdb_hetfa = nuclear.pulldown_4th_column_nickdb_hetfa
		analysis_files.pulldown_5th_column_nickdb_readgroup_diploid_source = nuclear.pulldown_5th_column_nickdb_readgroup_diploid_source
		analysis_files.save()

def move_pulldown_fields_to_nuclearanalysis(apps, schema_editor):
	NuclearAnalysis = apps.get_model('sequencing_run', 'NuclearAnalysis')
	AnalysisFiles = apps.get_model('sequencing_run', 'AnalysisFiles')
	
	for analysis_files in AnalysisFiles.objects.all():
		for nuclear in NuclearAnalysis.objects.filter(parent__exact=analysis_files.parent):
			nuclear.pulldown_logfile_location = analysis_files.pulldown_logfile_location
			nuclear.pulldown_1st_column_nickdb = analysis_files.pulldown_1st_column_nickdb
			nuclear.pulldown_2nd_column_nickdb_alt_sample = analysis_files.pulldown_2nd_column_nickdb_alt_sample
			nuclear.pulldown_3rd_column_nickdb_bam = analysis_files.pulldown_3rd_column_nickdb_bam
			nuclear.pulldown_4th_column_nickdb_hetfa = analysis_files.pulldown_4th_column_nickdb_hetfa
			nuclear.pulldown_5th_column_nickdb_readgroup_diploid_source = analysis_files.pulldown_5th_column_nickdb_readgroup_diploid_source
			nuclear.save()

class Migration(migrations.Migration):

    dependencies = [
        ('sequencing_run', '0010_auto_20200410_2252'),
    ]

    operations = [
		migrations.RunPython(move_pulldown_fields_to_analysisfiles, move_pulldown_fields_to_nuclearanalysis),
    ]
