# Generated by Django 3.0.4 on 2020-04-11 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
        ('sequencing_run', '0011_move_pulldown_fields_20200410_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nuclearanalysis',
            name='pulldown_1st_column_nickdb',
        ),
        migrations.RemoveField(
            model_name='nuclearanalysis',
            name='pulldown_2nd_column_nickdb_alt_sample',
        ),
        migrations.RemoveField(
            model_name='nuclearanalysis',
            name='pulldown_3rd_column_nickdb_bam',
        ),
        migrations.RemoveField(
            model_name='nuclearanalysis',
            name='pulldown_4th_column_nickdb_hetfa',
        ),
        migrations.RemoveField(
            model_name='nuclearanalysis',
            name='pulldown_5th_column_nickdb_readgroup_diploid_source',
        ),
        migrations.RemoveField(
            model_name='nuclearanalysis',
            name='pulldown_logfile_location',
        ),
        migrations.AlterField(
            model_name='analysisfiles',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.Results'),
        ),
    ]
