# Generated by Django 3.0.4 on 2020-04-13 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequencing_run', '0012_auto_20200411_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtanalysis',
            name='demultiplexing_sequences',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nuclearanalysis',
            name='assessment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='nuclearanalysis',
            name='bioinfo_processing_protocol',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='nuclearanalysis',
            name='find',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='nuclearanalysis',
            name='raw_reads_or_deindexing',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nuclearanalysis',
            name='results_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='nuclearanalysis',
            name='seq_run_file_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='nuclearanalysis',
            name='track_id_report_file',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='shotgunanalysis',
            name='bioinfo_processing_protocol',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='shotgunanalysis',
            name='raw_sequences',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shotgunanalysis',
            name='track_id',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='spikeanalysis',
            name='bioinfo_processing_protocol',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
