# Generated by Django 3.0.4 on 2020-04-16 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequencing_run', '0013_auto_20200412_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtanalysis',
            name='damage_restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nuclearanalysis',
            name='pulldown_logfile_location',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='shotgunanalysis',
            name='damage_restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spikeanalysis',
            name='damage_restricted',
            field=models.BooleanField(default=False),
        ),
    ]
