# Generated by Django 3.0.4 on 2020-04-16 01:35

from django.db import migrations

# Each nuclear analysis needs its matching pulldown log with correct damage restriction

# pulldown log files should be reloaded after this
def move_pulldown_log_to_nuclearanalysis(apps, schema_editor):
	NuclearAnalysis = apps.get_model('sequencing_run', 'NuclearAnalysis')
	AnalysisFiles = apps.get_model('sequencing_run', 'AnalysisFiles')
	
	for analysis_files in AnalysisFiles.objects.all():
		for nuclear in NuclearAnalysis.objects.filter(parent__exact=analysis_files.parent):
			nuclear.pulldown_logfile_location = analysis_files.pulldown_logfile_location
			nuclear.save()

# This will result in loss of data when there are two NuclearAnalysis objects for the same AnalysisFiles
# We assume this is OK because we will reload pulldown log files
def move_pulldown_log_to_analysisfiles(apps, schema_editor):
	NuclearAnalysis = apps.get_model('sequencing_run', 'NuclearAnalysis')
	AnalysisFiles = apps.get_model('sequencing_run', 'AnalysisFiles')
	
	# move the pulldown log from NuclearAnalysis to AnalysisFiles
	for nuclear in NuclearAnalysis.objects.all():
		analysis_files = AnalysisFiles.objects.get_or_create(parent__exact=nuclear.parent)
		analysis_files.pulldown_logfile_location = nuclear.pulldown_logfile_location

class Migration(migrations.Migration):

    dependencies = [
        ('sequencing_run', '0014_auto_20200415_2134'),
    ]

    operations = [
		migrations.RunPython(move_pulldown_log_to_nuclearanalysis, move_pulldown_log_to_analysisfiles),
    ]
