# Generated by Django 3.0.4 on 2020-04-16 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequencing_run', '0015_move_pulldown_log_20200415_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisfiles',
            name='pulldown_logfile_location',
        ),
    ]
