# Generated by Django 3.0.4 on 2021-04-28 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequencing_run', '0017_auto_20200615_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nuclearanalysis',
            old_name='assessment',
            new_name='assessment_notes',
        ),
    ]
