# Generated by Django 3.0.4 on 2021-04-28 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0034_auto_20210428_1808'),
        ('sequencing_run', '0018_auto_20210428_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuclearanalysis',
            name='assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samples.AssessmentCategory'),
        ),
    ]
