# Generated by Django 3.0.3 on 2025-10-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequencing_run', '0020_genetic_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='geneticanalysis',
            name='outlier_label',
            field=models.TextField(blank=True),
        ),
    ]
