# Generated by Django 3.0.3 on 2026-03-27 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0247_index_sample_externalid_individualid'),
        ('sequencing_run', '0021_geneticanalysis_outlier_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneticanalysis',
            name='assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.AssessmentCategory'),
        ),
        migrations.AlterField(
            model_name='nuclearanalysis',
            name='assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.AssessmentCategory'),
        ),
    ]
