# Generated by Django 3.0.3 on 2026-04-10 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0247_index_sample_externalid_individualid'),
        ('sequencing_run', '0022_protect_assessment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneticanalysis',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.AssessmentCategory'),
        ),
        migrations.AlterField(
            model_name='geneticanalysis',
            name='genotype_hash',
            field=models.CharField(blank=True, default='', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='geneticanalysis',
            name='missingness_hash',
            field=models.CharField(blank=True, default='', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='geneticanalysis',
            name='mt_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sequencing_run.MTAnalysis2'),
        ),
        migrations.AlterField(
            model_name='geneticanalysis',
            name='nuclear_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sequencing_run.NuclearAnalysis2'),
        ),
    ]
