# Generated by Django 3.0.3 on 2026-04-10 16:53

from django.db import migrations
from django.utils import timezone

def hash_fields_to_empty_string(apps, schema_editor):
	GeneticAnalysis = apps.get_model('sequencing_run', 'GeneticAnalysis')
	for x in GeneticAnalysis.objects.all():
		changed = False
		if x.genotype_hash is None:
			x.genotype_hash = ''
			changed = True
		if x.missingness_hash is None:
			x.missingness_hash = ''
			changed = True
		if changed:
			x.modification_timestamp = timezone.now()
			x.modified_by = 'migration'
			x.save()
			
def hash_fields_to_null(apps, schema_editor):
	GeneticAnalysis = apps.get_model('sequencing_run', 'GeneticAnalysis')
	for x in GeneticAnalysis.objects.all():
		changed = False
		if x.genotype_hash == '':
			x.genotype_hash = None
			changed = True
		if x.missingness_hash == '':
			x.missingness_hash = None
			changed = True
		if changed:
			x.modification_timestamp = timezone.now()
			x.modified_by = 'migration'
			x.save()

class Migration(migrations.Migration):

	dependencies = [
		('sequencing_run', '0023_genetic_analysis_blanks'),
	]

	operations = [
		migrations.RunPython(hash_fields_to_empty_string, hash_fields_to_null),
	]
