# Generated by Django 3.0.3 on 2026-04-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequencing_run', '0024_genetic_analysis_hash_empty_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneticanalysis',
            name='genotype_hash',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='geneticanalysis',
            name='missingness_hash',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
