# Generated by Django 3.0.3 on 2026-04-10 21:03

from django.db import migrations, models
import django.db.models.deletion
import samples.validation


class Migration(migrations.Migration):

    dependencies = [
        ('sequencing_run', '0025_genetic_analysis_hash_remove_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneticanalysis',
            name='genetic_id',
            field=models.TextField(db_index=True, unique=True, validators=[samples.validation.validate_alphanumeric_plus]),
        ),
        migrations.AlterField(
            model_name='geneticanalysis',
            name='outlier',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geneticanalysis',
            name='use_instead',
            field=models.ForeignKey(blank=True, help_text='This other analysis is an improvement and should be used instead.', null=True, on_delete=django.db.models.deletion.PROTECT, to='sequencing_run.GeneticAnalysis'),
        ),
    ]
