# Generated by Django 3.0.4 on 2020-04-16 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='extract_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.Extract'),
        ),
        migrations.AddField(
            model_name='library',
            name='library_batch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.LibraryBatch'),
        ),
    ]
