# Generated by Django 3.0.4 on 2020-04-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_auto_20200416_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarybatch',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='librarybatch',
            name='prep_robot',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
