# Generated by Django 3.0.4 on 2020-04-30 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_auto_20200416_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlsextract',
            name='nuclear_sequencing_run',
        ),
        migrations.RemoveField(
            model_name='controlslibrary',
            name='nuclear_sequencing_run',
        ),
        migrations.AddField(
            model_name='results',
            name='library_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samples.Library'),
        ),
    ]
