# Generated by Django 3.0.4 on 2020-05-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0006_fix_powdersamples'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='library_type',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
