# Generated by Django 3.0.4 on 2020-05-20 21:29

from django.db import migrations

# make a copy of the column udg_treatment as library_type in the Library model
def copy_udg_treatment_to_library_type(apps, schema_editor):
	Library = apps.get_model('samples', 'Library')
	
	for library in Library.objects.all():
		library.library_type = library.udg_treatment
		library.save()

class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0007_library_library_type'),
    ]

    operations = [
		migrations.RunPython(copy_udg_treatment_to_library_type),
    ]
