# Generated by Django 3.0.4 on 2020-05-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0008_copy_library_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sample_date',
            field=models.TextField(blank=True, help_text='Age of sample; either a radiocarbon date or a date interval.'),
        ),
    ]
