# Generated by Django 3.0.4 on 2020-05-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0013_auto_20200525_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequencingplatform',
            name='library_type',
        ),
        migrations.AddField(
            model_name='mtcaptureplate',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mtsequencingrun',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nuclearcaptureplate',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nuclearsequencingrun',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='powderbatch',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sequencingplatform',
            name='lanes_runs',
            field=models.FloatField(help_text='number of lanes for HISeqs or number of runs for Miseq and NextSeq', null=True),
        ),
        migrations.AddField(
            model_name='sequencingplatform',
            name='location',
            field=models.CharField(blank=True, help_text='location of sequencing platform', max_length=50),
        ),
        migrations.AddField(
            model_name='shotgunpool',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shotgunsequencingrun',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
