# Generated by Django 3.0.4 on 2020-06-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0015_auto_20200615_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='address_1',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='county_region',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='email_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='institution',
            field=models.CharField(blank=True, db_index=True, help_text="Collaborator's associated institution or company", max_length=100),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional information about collaborator'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='ora_approval',
            field=models.BooleanField(db_index=True, default=False, help_text='Has the Harvard office of Academic Research Integrity cleared this collaborator?'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='controlsextract',
            name='ec_count',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='controlsextract',
            name='ec_max',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='controlsextract',
            name='ec_median',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='controlslibrary',
            name='lc_count',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='controlslibrary',
            name='lc_max',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='controlslibrary',
            name='lc_median',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='distributionsshipment',
            name='date',
            field=models.DateField(help_text='Distribution shipment date', null=True),
        ),
        migrations.AlterField(
            model_name='distributionsshipment',
            name='shipment_method',
            field=models.CharField(blank=True, help_text='Shipment method used to send samples: FedEx, USPS, hand carried', max_length=20),
        ),
        migrations.AlterField(
            model_name='distributionsshipment',
            name='shipment_tracking_number',
            field=models.CharField(blank=True, help_text='Courier package tracking number', max_length=30),
        ),
        migrations.AlterField(
            model_name='library',
            name='assessment',
            field=models.TextField(blank=True, help_text='Xcontam listed if |Z|>2 standard errors from zero: 0.02-0.05="QUESTIONABLE", >0.05="QUESTIONABLE_CRITICAL" or "FAIL") (mtcontam 97.5th percentile estimates listed if coverage >2: <0.8 is "QUESTIONABLE_CRITICAL", 0.8-0.95 is "QUESTIONABLE", and 0.95-0.98 is recorded but "PASS", gets overriden by ANGSD'),
        ),
        migrations.AlterField(
            model_name='mtcaptureprotocol',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mtcaptureprotocol',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='mtcaptureprotocol',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='nuclearcaptureplate',
            name='hyb_wash_temps',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='nuclearcaptureplate',
            name='robot',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='nuclearcaptureprotocol',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='powderbatch',
            name='technician',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='powdersample',
            name='sampling_tech',
            field=models.CharField(blank=True, help_text='Technique used to produce the bone powder', max_length=15),
        ),
        migrations.AlterField(
            model_name='powdersample',
            name='storage_location',
            field=models.CharField(blank=True, help_text='Storage location of remaining bone powder', max_length=50),
        ),
        migrations.AlterField(
            model_name='publication',
            name='author_list',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='first_author',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='publication',
            name='journal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pages',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='publication',
            name='url',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='radiocarbondatinginvoice',
            name='billing_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='radiocarbondatinginvoice',
            name='billing_period',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='radiocarbondatinginvoice',
            name='company_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='radiocarbondatinginvoice',
            name='item_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='radiocarbondatinginvoice',
            name='total_charge',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='radiocarbonshipment',
            name='analysis_lab',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='return',
            name='return_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sampleprepprotocol',
            name='manuscript_summary',
            field=models.TextField(blank=True, help_text='Sampling method summary for manuscripts'),
        ),
        migrations.AlterField(
            model_name='sequencingplatform',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sequencingplatform',
            name='read_length',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='additional_information_location',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='arrival_method',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='arrival_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='documents_location',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='supportstaff',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='wetlabstaff',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
