# Generated by Django 3.0.4 on 2020-12-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0017_auto_20201202_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiocarbondatedsample',
            name='correction_note',
            field=models.TextField(blank=True),
        ),
    ]
