# Generated by Django 3.0.4 on 2020-12-03 23:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0018_radiocarbondatedsample_correction_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('modification_timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20)),
                ('country_name', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('subregion', models.CharField(blank=True, max_length=100)),
                ('intermediate_region', models.CharField(blank=True, max_length=100)),
                ('m49_code', models.PositiveSmallIntegerField(null=True)),
                ('iso_alpha2_code', models.CharField(blank=True, max_length=2)),
                ('iso_alpha3_code', models.CharField(blank=True, max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('modification_timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20)),
                ('abbreviation', models.CharField(max_length=10)),
                ('text', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('modification_timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20)),
                ('abbreviation', models.CharField(max_length=10)),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='accession_number',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='burial_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='pathology',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='publications',
            field=models.ManyToManyField(to='samples.Publication'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('modification_timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20)),
                ('level_1', models.CharField(blank=True, max_length=100)),
                ('level_2', models.CharField(blank=True, max_length=100)),
                ('level_3', models.CharField(blank=True, max_length=100)),
                ('level_4', models.CharField(blank=True, max_length=100)),
                ('level_5', models.CharField(blank=True, max_length=100)),
                ('site', models.TextField(blank=True)),
                ('latitude', models.CharField(blank=True, max_length=20)),
                ('longitude', models.CharField(blank=True, max_length=20)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='samples.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='country_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samples.Country'),
        ),
        migrations.AddField(
            model_name='sample',
            name='culture_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samples.Culture'),
        ),
        migrations.AddField(
            model_name='sample',
            name='location_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samples.Location'),
        ),
        migrations.AddField(
            model_name='sample',
            name='period_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samples.Period'),
        ),
    ]
