# Generated by Django 3.0.4 on 2021-01-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0020_radiocarbondatedsample_oxcal_sigma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture',
            name='abbreviation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='period',
            name='abbreviation',
            field=models.CharField(max_length=50),
        ),
    ]
