# Generated by Django 3.0.4 on 2021-01-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0021_auto_20210107_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='date_range',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='period',
            name='date_range',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='period',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
