# Generated by Django 3.0.4 on 2021-02-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0022_auto_20210119_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='date_fix_flag',
            field=models.TextField(blank=True, help_text='Flag for any issues with the date information submitted by the collaborator'),
        ),
    ]
