# Generated by Django 3.0.4 on 2021-02-08 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0023_auto_20210203_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='extract',
            name='reich_lab_extract_number',
            field=models.PositiveIntegerField(help_text='Starts at 1 for each lysate or sample if no lysate exists.', null=True),
        ),
        migrations.AddField(
            model_name='extract',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.Sample'),
        ),
        migrations.AddField(
            model_name='library',
            name='reich_lab_library_number',
            field=models.PositiveIntegerField(help_text='Starts at 1 for each extract or sample', null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.Sample'),
        ),
        migrations.AddField(
            model_name='lysate',
            name='reich_lab_lysate_number',
            field=models.PositiveIntegerField(help_text='Starts at 1 for each sample.', null=True),
        ),
    ]
