# Generated by Django 3.0.4 on 2021-02-11 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0025_fill_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extract',
            old_name='lysate_id',
            new_name='lysate',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='extract_id',
            new_name='extract',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='library_batch_id',
            new_name='library_batch',
        ),
    ]
