# Generated by Django 3.0.4 on 2021-02-11 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0026_auto_20210211_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='cultures',
            field=models.ManyToManyField(to='samples.Culture'),
        ),
        migrations.AddField(
            model_name='sample',
            name='periods',
            field=models.ManyToManyField(to='samples.Period'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='culture_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='culture_single', to='samples.Culture'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='period_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_single', to='samples.Period'),
        ),
    ]
