# Generated by Django 3.0.4 on 2021-02-11 20:43

from django.db import migrations

def periods(apps, schema_editor):
	Sample = apps.get_model('samples', 'Sample')
	for sample in Sample.objects.all():
		if sample.period_fk is not None:
			sample.periods.add(sample.period_fk)
			sample.save()

def cultures(apps, schema_editor):
	Sample = apps.get_model('samples', 'Sample')
	for sample in Sample.objects.all():
		if sample.culture_fk is not None:
			sample.cultures.add(sample.culture_fk)
			sample.save()

class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0027_auto_20210211_1536'),
    ]

    operations = [
		migrations.RunPython(periods, None),
		migrations.RunPython(cultures, None),
    ]
