# Generated by Django 3.0.4 on 2021-02-17 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0030_remove_location_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extract',
            old_name='extract_batch_id',
            new_name='extract_batch',
        ),
    ]
