# Generated by Django 3.0.4 on 2021-03-04 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0031_auto_20210217_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.Country'),
        ),
    ]
