# Generated by Django 3.0.4 on 2021-03-11 18:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0032_location_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('modification_timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20)),
                ('equipment_type', models.CharField(blank=True, max_length=50)),
                ('equipment_location', models.CharField(blank=True, max_length=50)),
                ('equipment_name', models.CharField(blank=True, max_length=50)),
                ('shelf', models.PositiveSmallIntegerField(null=True)),
                ('rack', models.PositiveSmallIntegerField(null=True)),
                ('drawer', models.PositiveSmallIntegerField(null=True)),
                ('unit_name', models.CharField(blank=True, max_length=50)),
                ('unit_type', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='extract',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.Storage'),
        ),
        migrations.AddField(
            model_name='lysate',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.Storage'),
        ),
        migrations.AddField(
            model_name='powdersample',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.Storage'),
        ),
    ]
