# Generated by Django 3.0.4 on 2021-04-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0033_auto_20210311_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=25, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.SmallIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='instance',
            old_name='assessment',
            new_name='assessment_notes',
        ),
    ]
