# Generated by Django 3.0.4 on 2021-04-28 22:27

from django.db import migrations

# add initial assessment categories
def add_inital_assessment_categories(apps, schema_editor):
	AssessmentCategory = apps.get_model('samples', 'AssessmentCategory')
	AssessmentCategory.objects.get_or_create(category='DoNotUse', sort_order=0)
	AssessmentCategory.objects.get_or_create(category='Fail', sort_order=10)
	AssessmentCategory.objects.get_or_create(category='QuestionableCritical', sort_order=20)
	AssessmentCategory.objects.get_or_create(category='Questionable', sort_order=30)
	AssessmentCategory.objects.get_or_create(category='Pass', sort_order=100)

class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0034_auto_20210428_1808'),
    ]

    operations = [
			migrations.RunPython(add_inital_assessment_categories),
    ]
