# Generated by Django 3.0.4 on 2021-05-12 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0037_auto_20210504_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowderBatchStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, unique=True)),
                ('sort_order', models.SmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='powderbatch',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samples.PowderBatchStatus'),
        ),
    ]
