# Generated by Django 3.0.4 on 2021-06-29 15:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import samples.models

def add_control_type_categories(apps, schema_editor):
	ControlType = apps.get_model('samples', 'ControlType')
	ControlType.objects.get_or_create(control_type='Extract Negative')
	ControlType.objects.get_or_create(control_type='Library Negative')
	ControlType.objects.get_or_create(control_type='Library Positive')
	ControlType.objects.get_or_create(control_type='PCR Positive')
	ControlType.objects.get_or_create(control_type='Capture Positive')
	
# values will automatically be destroyed by the table removal
def ignore_reverse(apps, schema_editor):
	pass

class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0039_powder_batch_status_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_type', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ControlLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('modification_timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20)),
                ('row', models.CharField(max_length=1, validators=[samples.models.validate_row_letter])),
                ('column', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('layout_name', models.CharField(db_index=True, max_length=25)),
                ('active', models.BooleanField(default=True)),
                ('control_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='samples.ControlType')),
            ],
            options={
                'abstract': False,
            },
        ),
		migrations.RunPython(add_control_type_categories, ignore_reverse),
    ]
