# Generated by Django 3.0.4 on 2021-07-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0040_controllayout_controltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionprotocol',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extractionprotocol',
            name='final_extract_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extractionprotocol',
            name='lysate_fraction_extracted',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extractionprotocol',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extractionprotocol',
            name='total_lysis_volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
