# Generated by Django 3.0.4 on 2021-07-15 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0042_auto_20210712_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='nanodrop',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='plate_id',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='position',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='qpcr',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='storage',
        ),
        migrations.AddField(
            model_name='library',
            name='barcode',
            field=models.CharField(blank=True, help_text='Physical barcode on FluidX tube', max_length=12),
        ),
        migrations.AddField(
            model_name='library',
            name='nanodrop',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='plate_id',
            field=models.CharField(blank=True, help_text='FluidX rack barcode', max_length=12),
        ),
        migrations.AddField(
            model_name='library',
            name='position',
            field=models.CharField(blank=True, help_text='well/tube position in plate/rack', max_length=3),
        ),
        migrations.AddField(
            model_name='library',
            name='qpcr',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.Storage'),
        ),
    ]
