# Generated by Django 3.0.4 on 2021-07-19 19:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0043_auto_20210715_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedComplexity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, unique=True)),
                ('sort_order', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SamplePrepQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('modification_timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20)),
                ('priority', models.SmallIntegerField(help_text='Lower is higher priority')),
                ('udg_treatment', models.CharField(max_length=10)),
                ('expected_complexity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samples.ExpectedComplexity')),
                ('powder_batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samples.PowderBatch')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.Sample')),
                ('sample_prep_protocol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samples.SamplePrepProtocol')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
