# Generated by Django 3.0.4 on 2021-07-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0045_expected_complexity_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractbatch',
            name='powder_batches',
            field=models.ManyToManyField(to='samples.PowderBatch'),
        ),
    ]
