# Generated by Django 3.0.4 on 2021-07-29 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0046_extractbatch_powder_batches'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleprepqueue',
            name='powder_sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samples.PowderSample'),
        ),
    ]
