# Generated by Django 3.0.4 on 2021-07-30 19:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import samples.models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0047_sampleprepqueue_powder_sample'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractBatchLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('modification_timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20)),
                ('row', models.CharField(max_length=1, validators=[samples.models.validate_row_letter])),
                ('column', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('extract_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.ExtractBatch')),
                ('powder_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.PowderSample')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='extractbatch',
            name='layout',
            field=models.ManyToManyField(through='samples.ExtractBatchLayout', to='samples.PowderSample'),
        ),
    ]
