# Generated by Django 3.0.4 on 2021-08-06 21:21

from django.db import migrations

def closed_to_in_progress(apps, schema_editor):
	PowderBatchStatus = apps.get_model('samples', 'PowderBatchStatus')
	powder_batch_status = PowderBatchStatus.objects.get(description='Closed')
	powder_batch_status.description = 'In Progress'
	powder_batch_status.save()
	
def in_progress_to_closed(apps, schema_editor):
	PowderBatchStatus = apps.get_model('samples', 'PowderBatchStatus')
	powder_batch_status = PowderBatchStatus.objects.get(description='In Progress')
	powder_batch_status.description = 'Closed'
	powder_batch_status.save()


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0049_auto_20210730_1541'),
    ]

    operations = [
		migrations.RunPython(closed_to_in_progress, in_progress_to_closed),
    ]
