# Generated by Django 3.0.4 on 2021-08-10 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0050_rename_closed_powder_batch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractbatchlayout',
            name='control_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.ControlType'),
        ),
        migrations.AddField(
            model_name='extractbatchlayout',
            name='powder_used_mg',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extractbatch',
            name='layout',
            field=models.ManyToManyField(related_name='powder_sample_assignment', through='samples.ExtractBatchLayout', to='samples.PowderSample'),
        ),
        migrations.AlterField(
            model_name='extractbatchlayout',
            name='powder_sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='samples.PowderSample'),
        ),
    ]
