# Generated by Django 3.0.4 on 2021-08-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0051_auto_20210810_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='powdersample',
            name='powder_for_extract',
            field=models.FloatField(default=0, help_text='Milligrams of powder used for extract'),
        ),
        migrations.AlterField(
            model_name='distributionspowder',
            name='powder_sent_mg',
            field=models.FloatField(help_text='Total milligrams of bone powder distributed'),
        ),
        migrations.AlterField(
            model_name='powdersample',
            name='total_powder_produced_mg',
            field=models.FloatField(help_text='Total milligrams of bone powder produced from the sample', null=True),
        ),
    ]
