# Generated by Django 3.0.4 on 2021-08-17 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0052_auto_20210812_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='expected_complexity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samples.ExpectedComplexity'),
        ),
        migrations.AlterField(
            model_name='extractbatch',
            name='date',
            field=models.DateField(help_text='YYYY-MM-DD', null=True),
        ),
    ]
