# Generated by Django 3.0.4 on 2021-08-17 18:33

from django.db import migrations

def copy_expected_complexity_from_sample_prep_queue_to_sample(apps, schema_editor):
	Sample = apps.get_model('samples', 'Sample')
	SamplePrepQueue = apps.get_model('samples', 'SamplePrepQueue')
	
	for sample_prep_queue in SamplePrepQueue.objects.all():
		sample = sample_prep_queue.sample
		if sample.expected_complexity is None:
			sample.expected_complexity = sample_prep_queue.expected_complexity
		elif sample.expected_complexity != sample_prep_queue.expected_complexity:
			raise ValueError(f'sample {sample.id}: nonmatching expected complexity {sample_prep_queue.expected_complexity}')
		sample.save()
	
def copy_expected_complexity_from_sample_to_sample_prep_queue(apps, schema_editor):
	Sample = apps.get_model('samples', 'Sample')
	SamplePrepQueue = apps.get_model('samples', 'SamplePrepQueue')
	
	for sample in Sample.objects.all():
		prep_queue_entries = SamplePrepQueue.objects.filter(sample=sample)
		for sample_prep_queue in prep_queue_entries:
			sample_prep_queue.expected_complexity = sample.expected_complexity
			sample_prep_queue.save()

class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0053_auto_20210817_1418'),
    ]

    operations = [
		migrations.RunPython(copy_expected_complexity_from_sample_prep_queue_to_sample, copy_expected_complexity_from_sample_to_sample_prep_queue),
    ]
