# Generated by Django 3.0.4 on 2021-08-17 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0054_sample_expected_complexity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleprepqueue',
            name='expected_complexity',
        ),
    ]
