# Generated by Django 3.0.4 on 2021-09-01 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0055_remove_sampleprepqueue_expected_complexity'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractbatch',
            name='control_layout_name',
            field=models.CharField(blank=True, help_text='When applying a layout, use this set of controls.  The control entries are stored in layout.', max_length=25),
        ),
        migrations.AlterField(
            model_name='extractbatchlayout',
            name='extract_batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='samples.ExtractBatch'),
        ),
    ]
