# Generated by Django 3.0.4 on 2021-09-17 17:59

from django.db import migrations

PCR_NEGATIVE = 'PCR Negative'
PCR_POSITIVE = 'PCR Positive'

# correct to PCR Negative
def pcr_negative(apps, schema_editor):
	ControlType = apps.get_model('samples', 'ControlType')
	control_type = ControlType.objects.get(control_type=PCR_POSITIVE)
	control_type.control_type = PCR_NEGATIVE
	control_type.save()
	
# incorrect was PCR Positive
def pcr_positive(apps, schema_editor):
	ControlType = apps.get_model('samples', 'ControlType')
	control_type = ControlType.objects.get(control_type=PCR_NEGATIVE)
	control_type.control_type = PCR_POSITIVE
	control_type.save()

class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0056_auto_20210901_1403'),
    ]

    operations = [
		migrations.RunPython(pcr_negative, pcr_positive),
    ]
