# Generated by Django 3.0.4 on 2021-09-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0057_correct_pcr_control_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='control',
            field=models.CharField(blank=True, help_text='Non-empty value indicates this is a control', max_length=2),
        ),
    ]
