# Generated by Django 3.0.4 on 2021-09-28 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0058_auto_20210923_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractbatch',
            name='powder_batches',
        ),
    ]
