# Generated by Django 3.0.4 on 2021-09-29 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0059_remove_extractbatch_powder_batches'),
    ]

    operations = [
		migrations.RenameModel('ExtractBatch', 'LysateBatch'),
		migrations.RenameModel('ExtractBatchLayout', 'LysateBatchLayout'),
    ]
