# Generated by Django 3.0.4 on 2021-09-29 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0060_rename_extract_batch_to_lysate_batch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlsextract',
            old_name='extract_batch',
            new_name='lysate_batch',
        ),
        migrations.RenameField(
            model_name='extract',
            old_name='extract_batch',
            new_name='lysate_batch',
        ),
        migrations.RenameField(
            model_name='lysatebatchlayout',
            old_name='extract_batch',
            new_name='lysate_batch',
        ),
    ]
