# Generated by Django 3.0.4 on 2021-10-01 20:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import samples.models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0061_auto_20210929_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('modification_timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20)),
                ('batch_name', models.CharField(max_length=50, unique=True)),
                ('technician', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField(help_text='YYYY-MM-DD', null=True)),
                ('robot', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('control_layout_name', models.CharField(blank=True, help_text='When applying a layout, use this set of controls.  The control entries are stored in layout.', max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExtractionBatchLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('modification_timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20)),
                ('row', models.CharField(max_length=1, validators=[samples.models.validate_row_letter])),
                ('column', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('lysate_volume_used', models.FloatField()),
                ('control_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.ControlType')),
                ('extract_batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='samples.ExtractionBatch')),
                ('lysate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='samples.Lysate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='extractionbatch',
            name='layout',
            field=models.ManyToManyField(related_name='lysate_assignment', through='samples.ExtractionBatchLayout', to='samples.Lysate'),
        ),
        migrations.AddField(
            model_name='extractionbatch',
            name='protocol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.ExtractionProtocol'),
        ),
        migrations.AddField(
            model_name='extractionbatch',
            name='technician_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samples.WetLabStaff'),
        ),
    ]
