# Generated by Django 3.0.4 on 2021-10-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0062_auto_20211001_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionbatchlayout',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lysatebatchlayout',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
