# Generated by Django 3.0.4 on 2021-10-09 08:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import samples.layout


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0063_auto_20211003_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryBatchLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('modification_timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20)),
                ('row', models.CharField(max_length=1, validators=[samples.layout.validate_row_letter])),
                ('column', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('ul_extract_used', models.FloatField()),
                ('notes', models.TextField(blank=True)),
                ('control_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.ControlType')),
                ('extract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='samples.Extract')),
                ('library_batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='samples.LibraryBatch')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
