# Generated by Django 3.0.4 on 2021-10-09 09:30

from django.db import migrations, models
import django.db.models.deletion
import samples.models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0064_librarybatchlayout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, max_length=10)),
                ('sequence', models.CharField(db_index=True, max_length=30, unique=True, validators=[samples.models.validate_barcode_dna_sequence])),
            ],
        ),
        migrations.CreateModel(
            name='P5_Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, max_length=10)),
                ('label2', models.CharField(max_length=20)),
                ('sequence', models.CharField(db_index=True, max_length=8, unique=True, validators=[samples.models.validate_index_dna_sequence])),
            ],
        ),
        migrations.CreateModel(
            name='P7_Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, max_length=10)),
                ('label2', models.CharField(max_length=20)),
                ('sequence', models.CharField(db_index=True, max_length=8, unique=True, validators=[samples.models.validate_index_dna_sequence])),
            ],
        ),
        migrations.AddField(
            model_name='library',
            name='p5_barcode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p5_barcode', to='samples.Barcode'),
        ),
        migrations.AddField(
            model_name='library',
            name='p5_index',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.P5_Index'),
        ),
        migrations.AddField(
            model_name='library',
            name='p7_barcode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p7_barcode', to='samples.Barcode'),
        ),
        migrations.AddField(
            model_name='library',
            name='p7_index',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.P7_Index'),
        ),
    ]
