# Generated by Django 3.0.4 on 2021-10-10 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0065_auto_20211009_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='extract',
            name='extract_batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.ExtractionBatch'),
        ),
        migrations.AddField(
            model_name='lysate',
            name='lysate_batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samples.LysateBatch'),
        ),
    ]
