# Generated by Django 3.0.4 on 2021-10-12 21:00

from django.db import migrations, models
import samples.models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0066_auto_20211009_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='sequence',
            field=models.CharField(db_index=True, max_length=31, unique=True, validators=[samples.models.validate_barcode_dna_sequence]),
        ),
        migrations.AlterField(
            model_name='p5_index',
            name='label2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='p7_index',
            name='label2',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
