# Generated by Django 3.0.4 on 2021-10-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0070_lysatebatch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lysatebatch',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Open'), (1, 'Lysates created')], default=0),
        ),
    ]
