# Generated by Django 3.0.4 on 2021-10-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0072_extractionbatch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarybatch',
            name='cleanup_robot',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='librarybatch',
            name='qpcr_machine',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
