# Generated by Django 3.0.4 on 2021-10-19 19:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0074_lysatebatchlayout_lysate'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionbatchlayout',
            name='extract',
            field=models.ForeignKey(help_text='extract created in this well location', null=True, on_delete=django.db.models.deletion.SET_NULL, to='samples.Extract'),
        ),
        migrations.AlterField(
            model_name='librarybatch',
            name='p7_offset',
            field=models.SmallIntegerField(help_text='Must be even in [0,46]', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(47)]),
        ),
    ]
