# Generated by Django 3.0.4 on 2021-10-20 02:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import samples.models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0075_auto_20211019_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarybatchlayout',
            name='library',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samples.Library'),
        ),
        migrations.AlterField(
            model_name='librarybatch',
            name='p7_offset',
            field=models.SmallIntegerField(help_text='Must be even in [0,46]', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(47), samples.models.validate_even]),
        ),
    ]
