# Generated by Django 3.0.4 on 2021-10-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0076_library_batch_and_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarybatchlayout',
            name='ul_extract_used',
            field=models.FloatField(null=True),
        ),
    ]
