# Generated by Django 3.0.4 on 2021-10-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0077_librarybatchlayout_ul_extract_used_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarybatch',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Open'), (1, 'Libraried')], default=1),
        ),
    ]
