# Generated by Django 3.0.4 on 2021-10-26 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0081_control_set_additions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controllayout',
            name='layout_name',
        ),
        migrations.RemoveField(
            model_name='extractionbatch',
            name='control_layout_name',
        ),
        migrations.RemoveField(
            model_name='lysatebatch',
            name='control_layout_name',
        ),
    ]
