# Generated by Django 3.0.4 on 2021-10-29 22:03

from django.db import migrations

def do_nothing(apps, schema_editor):
	pass

# this is for the reverse step of going backwards from one SequencingRun table to the three separate ones for Nuclear, MT, and Shotgun
def separate_sequencing_runs_results_references(apps, schema_editor):
	Results = apps.get_model('samples', 'Results')
	NuclearSequencingRun = apps.get_model('samples', 'NuclearSequencingRun')
	MTSequencingRun = apps.get_model('samples', 'MTSequencingRun')
	ShotgunSequencingRun = apps.get_model('samples', 'ShotgunSequencingRun')
	
	for results in Results.objects.all():
		
		mt = results.mt_seq_run_temp
		if mt is not None:
			results.mt_seq_run = MTSequencingRun.objects.get(name=mt.name)
		
		shotgun = results.shotgun_seq_run_temp
		if shotgun is not None:
			results.shotgun_seq_run = ShotgunSequencingRun.objects.get(name=shotgun.name)
		
		nuclear = results.nuclear_seq_run_temp
		if nuclear is not None:
			results.nuclear_seq_run = NuclearSequencingRun.objects.get(name=nuclear.name)
		
		results.save()


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0086_uniform_sequencing_run_length'),
    ]

    operations = [
		migrations.RunPython(do_nothing, separate_sequencing_runs_results_references),
    ]
