# Generated by Django 3.0.4 on 2021-10-29 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0088_reverse_repopulate_separate_sequencing_runs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nuclearsequencingrun',
            name='sequencing',
        ),
        migrations.RemoveField(
            model_name='nuclearsequencingrun',
            name='technician_fk',
        ),
        migrations.RemoveField(
            model_name='shotgunsequencingrun',
            name='sequencing',
        ),
        migrations.RemoveField(
            model_name='shotgunsequencingrun',
            name='technician_fk',
        ),
        migrations.RemoveField(
            model_name='results',
            name='mt_seq_run',
        ),
        migrations.RemoveField(
            model_name='results',
            name='nuclear_seq_run',
        ),
        migrations.RemoveField(
            model_name='results',
            name='shotgun_seq_run',
        ),
        migrations.DeleteModel(
            name='MTSequencingRun',
        ),
        migrations.DeleteModel(
            name='NuclearSequencingRun',
        ),
        migrations.DeleteModel(
            name='ShotgunSequencingRun',
        ),
    ]
