# Generated by Django 3.0.4 on 2021-10-29 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0089_remove_obsolete_sequencing_runs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='results',
            old_name='mt_seq_run_temp',
            new_name='mt_seq_run',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='nuclear_seq_run_temp',
            new_name='nuclear_seq_run',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='shotgun_seq_run_temp',
            new_name='shotgun_seq_run',
        ),
    ]
