# Generated by Django 3.0.4 on 2021-11-01 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0090_auto_20211029_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extract',
            name='extract_batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='samples.ExtractionBatch'),
        ),
        migrations.AlterField(
            model_name='library',
            name='library_batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='samples.LibraryBatch'),
        ),
        migrations.AlterField(
            model_name='lysate',
            name='lysate_batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='samples.LysateBatch'),
        ),
        migrations.AlterField(
            model_name='powdersample',
            name='powder_batch',
            field=models.ForeignKey(help_text='powder belongs to this processing batch', null=True, on_delete=django.db.models.deletion.CASCADE, to='samples.PowderBatch'),
        ),
    ]
