# Generated by Django 3.0.4 on 2021-11-05 05:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import samples.layout


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0091_cascade_on_batch_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuclearcaptureplate',
            name='p5_index_start',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nuclearcaptureplate',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='CaptureLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('modification_timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20)),
                ('row', models.CharField(max_length=1, validators=[samples.layout.validate_row_letter])),
                ('column', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('notes', models.TextField(blank=True)),
                ('capture_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.NuclearCapturePlate')),
                ('control_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.ControlType')),
                ('library', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='samples.Library')),
                ('p5_index', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.P5_Index')),
                ('p7_index', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.P7_Index')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sequencingrun',
            name='indexed_libraries',
            field=models.ManyToManyField(to='samples.CaptureLayout'),
        ),
    ]
