# Generated by Django 3.0.4 on 2021-11-05 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0092_auto_20211105_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarybatch',
            name='control_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samples.ControlSet'),
        ),
    ]
