# Generated by Django 3.0.4 on 2021-11-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0100_remove_specific_capture_protocol_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captureprotocol',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
