# Generated by Django 3.0.4 on 2021-11-11 18:13

from django.db import migrations, models
import django.db.models.deletion

def assign_shotgun_protocol_to_shotgun_pool_entries(apps, schema_editor):
	CaptureProtocol = apps.get_model('samples', 'CaptureProtocol')
	shotgun = CaptureProtocol.objects.get(name='Raw')
	ShotgunPool = apps.get_model('samples', 'ShotgunPool')
	for x in ShotgunPool.objects.all():
		x.protocol_temp = shotgun
		x.save()
	
def do_nothing(apps, schema_editor):
	pass

class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0103_shotgun_protocol_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='shotgunpool',
            name='protocol_temp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.CaptureProtocol'),
        ),
		migrations.RunPython(assign_shotgun_protocol_to_shotgun_pool_entries, do_nothing),
    ]
