# Generated by Django 3.0.4 on 2021-11-11 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0107_results_capture_references_fill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shotgunpool',
            name='protocol_temp',
        ),
        migrations.RemoveField(
            model_name='shotgunpool',
            name='technician_fk',
        ),
        migrations.RemoveField(
            model_name='results',
            name='mt_capture_plate',
        ),
        migrations.RemoveField(
            model_name='results',
            name='shotgun_pool',
        ),
        migrations.DeleteModel(
            name='MTCapturePlate',
        ),
        migrations.DeleteModel(
            name='ShotgunPool',
        ),
    ]
