# Generated by Django 3.0.4 on 2021-11-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0110_remame_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencingplatform',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
