# Generated by Django 3.0.4 on 2021-11-12 00:49

from django.db import migrations

def copy_powder_batch_status(apps, queryset):
	PowderBatch = apps.get_model('samples', 'PowderBatch')
	
	for x in PowderBatch.objects.all():
		if x.status:
			x.status_int = x.status.sort_order
		x.save()

class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0112_powder_batch_status'),
    ]

    operations = [
		migrations.RunPython(copy_powder_batch_status),
    ]
