# Generated by Django 3.0.4 on 2021-11-12 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0114_auto_20211111_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='powderbatch',
            old_name='status_int',
            new_name='status',
        ),
    ]
