# Generated by Django 3.0.4 on 2021-11-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0115_rename_powder_batch_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequencingrun',
            old_name='date',
            new_name='date_pooled',
        ),
        migrations.AddField(
            model_name='sequencingrun',
            name='date_analysis_complete',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sequencingrun',
            name='date_analysis_started',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sequencingrun',
            name='date_data_available',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sequencingrun',
            name='date_pulldown_complete',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sequencingrun',
            name='date_ready_for_pulldown',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sequencingrun',
            name='date_ready_for_sequencing',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sequencingrun',
            name='date_submitted_for_sequencing',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sequencingrun',
            name='lanes_estimated',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sequencingrun',
            name='lanes_sequenced',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sequencingrun',
            name='reich_lab_release_version',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
