# Generated by Django 3.0.4 on 2021-11-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0116_sequencing_run_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='captureorshotgunplate',
            name='needs_sequencing',
            field=models.BooleanField(default=False),
        ),
    ]
