# Generated by Django 3.0.4 on 2021-11-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0117_captureorshotgunplate_needs_sequencing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captureorshotgunplate',
            name='needs_sequencing',
            field=models.BooleanField(default=True, help_text='True normally. False for historical plates.'),
        ),
    ]
