# Generated by Django 3.0.4 on 2021-11-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0118_default_needs_sequencing'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencingrun',
            name='captures',
            field=models.ManyToManyField(to='samples.CaptureOrShotgunPlate'),
        ),
    ]
