# Generated by Django 3.0.4 on 2021-11-16 20:54

from django.db import migrations

def remove_orphan_control_layouts(apps, queryset):
	ControlLayout = apps.get_model('samples', 'ControlLayout')
	for x in ControlLayout.objects.filter(control_set=None):
		x.delete()

def orphans_never_needed(apps, queryset):
	pass

class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0120_auto_20211116_1048'),
    ]

    operations = [
		migrations.RunPython(remove_orphan_control_layouts, orphans_never_needed),
    ]
