# Generated by Django 3.0.4 on 2021-11-16 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0121_remove_orphan_control_layouts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controllayout',
            name='control_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.ControlSet'),
        ),
    ]
