# Generated by Django 3.0.4 on 2021-11-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0122_control_layout_sets_nonnull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captureorshotgunplate',
            name='name',
            field=models.CharField(help_text='Usually ends with _TW or _RW', max_length=50),
        ),
        migrations.AlterField(
            model_name='extractionbatch',
            name='batch_name',
            field=models.CharField(help_text='Usually ends with _RE', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='librarybatch',
            name='name',
            field=models.CharField(blank=True, help_text='Usually ends with _DS', max_length=150),
        ),
        migrations.AlterField(
            model_name='lysatebatch',
            name='batch_name',
            field=models.CharField(help_text='Usually ends with _LY', max_length=50, unique=True),
        ),
    ]
