# Generated by Django 3.0.4 on 2021-11-19 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0123_batch_name_hints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='barcode',
            new_name='fluidx_barcode',
        ),
    ]
