# Generated by Django 3.0.4 on 2021-11-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0124_rename_fluidx_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='nanodrop',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='qpcr',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
