# Generated by Django 3.0.4 on 2021-11-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0125_nanodrop_qpcr_decimal_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='captureorshotgunplate',
            name='reagent_batch',
            field=models.PositiveSmallIntegerField(help_text='Twist batch or bait batch number', null=True),
        ),
    ]
