# Generated by Django 3.0.4 on 2021-11-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0126_captureorshotgunplate_reagent_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='controllayout',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
