# Generated by Django 3.0.4 on 2021-11-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0129_captureorshotgunplate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captureorshotgunplate',
            name='status',
            field=models.SmallIntegerField(choices=[(-100, 'Stop'), (0, 'Open'), (100, 'In Progress'), (200, 'Closed')], default=0),
        ),
    ]
