# Generated by Django 3.0.4 on 2021-11-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0131_lanes_of_sequencing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencingrun',
            name='date_pooled',
            field=models.DateField(help_text='When date is set, captures can no longer be assigned.', null=True),
        ),
        migrations.AlterField(
            model_name='sequencingrun',
            name='lanes_sequenced',
            field=models.PositiveSmallIntegerField(help_text='number of lanes for HISeqs or number of runs for Miseq and NextSeq', null=True),
        ),
    ]
