# Generated by Django 3.0.4 on 2021-11-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0132_auto_20211122_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencingrun',
            name='read_length',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
