# Generated by Django 3.0.4 on 2021-11-22 14:56

from django.db import migrations

def copy_read_length_from_sequencing_platform_to_sequencing_run(apps, queryset):
	SequencingRun = apps.get_model('samples', 'SequencingRun')
	for run in SequencingRun.objects.all():
		sequencing_platform = run.sequencing
		if sequencing_platform:
			run.read_length = sequencing_platform.read_length
			run.save()
			
def do_nothing(apps, queryset):
	pass

class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0133_sequencingrun_read_length'),
    ]

    operations = [
		migrations.RunPython(copy_read_length_from_sequencing_platform_to_sequencing_run, do_nothing),
    ]
