# Generated by Django 3.0.4 on 2021-11-22 15:22

from django.db import migrations
from django.db.models import Count

def remove_empty_sequencing_platform(apps, queryset):
	SequencingRun = apps.get_model('samples', 'SequencingRun')
	SequencingPlatform = apps.get_model('samples', 'SequencingPlatform')
	
	platforms = SequencingPlatform.objects.annotate(run_count=Count('sequencingrun'))
	for platform in platforms:
		#print(f'{platform.platform} {platform.run_count}')
		if platform.run_count == 0:
			platform.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0135_sequencing_platform_merge'),
    ]

    operations = [
		migrations.RunPython(remove_empty_sequencing_platform),
    ]
