# Generated by Django 3.0.4 on 2021-11-22 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0136_remove_empty_sequencing_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequencingplatform',
            name='lanes_runs',
        ),
        migrations.RemoveField(
            model_name='sequencingplatform',
            name='read_length',
        ),
    ]
