# Generated by Django 3.0.4 on 2021-12-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0139_powder_batch_closed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionbatchlayout',
            name='lysate_volume_used',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='lysatebatchlayout',
            name='powder_used_mg',
            field=models.FloatField(null=True),
        ),
    ]
