# Generated by Django 3.0.4 on 2021-12-02 16:21

from django.db import migrations
from django.db.models import Count, Q

def close_old_powder_batches(apps, queryset):
	PowderBatch = apps.get_model('samples', 'PowderBatch')
	for powder_batch in PowderBatch.objects.all():
		# cannot call model methods, so need to copy code here
		expected = powder_batch.powdersample_set.all().count()
		assigned = powder_batch.powdersample_set.annotate(num_assignments=Count('lysatebatchlayout', Q(lysatebatchlayout__lysate_batch__isnull=False))).filter(num_assignments__gte=1).count()
		if assigned == expected:
			powder_batch.status = 300 #powder_batch.CLOSED
			powder_batch.save()

def do_nothing(apps, queryset):
	pass

class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0141_lysate_batches_and_extract_batches'),
    ]

    operations = [
		migrations.RunPython(close_old_powder_batches, do_nothing),
    ]
