# Generated by Django 3.0.4 on 2021-12-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0144_library_layouts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarybatch',
            name='name',
            field=models.CharField(blank=True, help_text='Usually ends with _DS', max_length=150, unique=True),
        ),
    ]
