# Generated by Django 3.0.4 on 2022-01-26 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0145_unique_library_batch_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkeletalElementCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=50)),
                ('sort_order', models.PositiveSmallIntegerField(default=1, help_text='For changing display order of categories in web interface')),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='skeletal_element_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.SkeletalElementCategory'),
        ),
    ]
