# Generated by Django 3.0.4 on 2021-12-09 18:44

from django.db import migrations, models

def null_lysate_batch_indicates_lost(apps, extract_id):
	LysateBatchLayout = apps.get_model('samples', 'LysateBatchLayout')
	for element in LysateBatchLayout.objects.all():
		if element.lysate_batch is None:
			element.is_lost = True
			element.save()

	
def do_nothing(apps, extract_id):
	pass

class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0145_unique_library_batch_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='lysatebatchlayout',
            name='is_lost',
            field=models.BooleanField(default=False),
        ),
		migrations.RunPython(null_lysate_batch_indicates_lost, do_nothing),
    ]
