# Generated by Django 3.0.4 on 2022-01-26 22:14

from django.db import migrations

# Skeletal element contains clean label information
def create_categories(apps, queryset):
	Sample = apps.get_model('samples', 'Sample')
	SkeletalElementCategory = apps.get_model('samples', 'SkeletalElementCategory')
	skeletal_elements = Sample.objects.values_list('skeletal_element', flat=True).distinct()
	for skeletal_element in skeletal_elements:
		SkeletalElementCategory.objects.get_or_create(category=skeletal_element)
		
# create foreign key link for 
def link_categories(apps, queryset):
	Sample = apps.get_model('samples', 'Sample')
	SkeletalElementCategory = apps.get_model('samples', 'SkeletalElementCategory')
	for sample in Sample.objects.all():
		sample.skeletal_element_category = SkeletalElementCategory.objects.get(category=sample.skeletal_element)
		sample.save()

def do_nothing(apps, queryset):
	pass

class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0146_auto_20220126_1713'),
    ]

    operations = [
		migrations.RunPython(create_categories, do_nothing),
		migrations.RunPython(link_categories, do_nothing),
    ]
