# Generated by Django 3.0.4 on 2021-12-13 18:28

from django.db import migrations

def ready_for_plate_layout_elements(apps, queryset):
	PowderSample = apps.get_model('samples', 'PowderSample')
	LysateBatchLayout = apps.get_model('samples', 'LysateBatchLayout')
	needs_layout_element = PowderSample.objects.filter(powder_batch__status=200)
	for powder_sample in needs_layout_element:
		LysateBatchLayout.objects.get_or_create(powder_sample=powder_sample, powder_used_mg=powder_sample.powder_for_extract)

class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0146_lysatebatchlayout_is_lost'),
    ]

    operations = [
		migrations.RunPython(ready_for_plate_layout_elements),
    ]
