# Generated by Django 3.0.4 on 2021-12-15 16:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0147_lysate_batch_elements_for_powder_samples'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleprepqueue',
            name='prepared_powder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samples.LysateBatchLayout'),
        ),
        migrations.CreateModel(
            name='PowderPrepQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('modification_timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20)),
                ('priority', models.SmallIntegerField(help_text='Lower is higher priority')),
                ('udg_treatment', models.CharField(max_length=10)),
                ('sample_prep_lab', models.CharField(blank=True, help_text='Name of lab where bone powder was produced', max_length=50)),
                ('powder_batch', models.ForeignKey(help_text='Powder batch where weighed for lysate', null=True, on_delete=django.db.models.deletion.SET_NULL, to='samples.PowderBatch')),
                ('powder_sample', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samples.PowderSample')),
                ('prepared_powder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samples.LysateBatchLayout')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.Sample')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
