# Generated by Django 3.0.4 on 2021-12-16 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0148_powder_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='powderprepqueue',
            name='sample_prep_protocol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samples.SamplePrepProtocol'),
        ),
    ]
