# Generated by Django 3.0.4 on 2022-03-29 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0147_skeletal_element_category'),
        ('samples', '0149_powderprepqueue_sample_prep_protocol'),
    ]

    operations = [
    ]
