# Generated by Django 3.0.4 on 2022-04-05 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0150_merge_20220329_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='lysatebatchlayout',
            name='powder_batch',
            field=models.ForeignKey(help_text='Powder batch where powder was weighed', null=True, on_delete=django.db.models.deletion.CASCADE, to='samples.PowderBatch'),
        ),
    ]
