# Generated by Django 3.0.4 on 2022-06-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0152_lysate_batch_layout_back_powder_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencingrun',
            name='lanes_estimated',
            field=models.FloatField(null=True),
        ),
    ]
