# Generated by Django 3.0.4 on 2022-06-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0153_auto_20220607_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarybatch',
            name='cleanup_date',
            field=models.DateField(help_text='YYYY-MM-DD', null=True),
        ),
        migrations.AddField(
            model_name='librarybatch',
            name='cleanup_person',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
