# Generated by Django 3.0.4 on 2022-06-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0155_longer_ids_for_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionbatch',
            name='rotated',
            field=models.BooleanField(default=False, help_text='True for second extract plates that are rotated 180 degrees'),
        ),
        migrations.AddField(
            model_name='librarybatch',
            name='rotated',
            field=models.BooleanField(default=False, help_text='True for second extract plates that are rotated 180 degrees'),
        ),
    ]
