# Generated by Django 3.0.4 on 2022-07-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0157_capture_positive_ds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('analysis_reporting', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('collaborators', models.ManyToManyField(to='samples.Collaborator')),
                ('samples', models.ManyToManyField(to='samples.Sample')),
            ],
        ),
    ]
