# Generated by Django 3.0.4 on 2022-07-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0158_projects_organizing_collaborators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionbatch',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='librarybatch',
            name='cleanup_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='librarybatch',
            name='prep_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='lysatebatch',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='powderbatch',
            name='date',
            field=models.DateField(help_text='Date batch was powdered', null=True),
        ),
    ]
