# Generated by Django 3.0.4 on 2022-07-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0159_date_picker_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiocarbondatedsample',
            name='material_returned',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='radiocarbondatedsample',
            name='sample_grams',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='radiocarbondatedsample',
            name='skeletal_element_sent',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
