# Generated by Django 3.0.4 on 2022-08-05 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0162_auto_20220722_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='lysate',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.Sample'),
        ),
    ]
