# Generated by Django 3.0.4 on 2022-08-05 21:02

from django.db import migrations

def fill_lysate_sample(apps, queryset):
	Lysate = apps.get_model('samples', 'Lysate')
	for lysate in Lysate.objects.all():
		lysate.sample = lysate.powder_sample.sample
		lysate.save()

def do_nothing(apps, queryset):
	pass

class Migration(migrations.Migration):

	dependencies = [
		('samples', '0163_lysate_sample'),
	]

	operations = [
		migrations.RunPython(fill_lysate_sample, do_nothing),
	]
