# Generated by Django 3.0.4 on 2022-08-05 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0164_fill_lysate_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlslibrary',
            name='library_batch',
        ),
        migrations.RemoveField(
            model_name='results',
            name='extract_control',
        ),
        migrations.RemoveField(
            model_name='results',
            name='library_control',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='country',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='country_fk',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='geo_region',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='geo_subregion',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='longitude',
        ),
        migrations.DeleteModel(
            name='ControlsExtract',
        ),
        migrations.DeleteModel(
            name='ControlsLibrary',
        ),
    ]
