# Generated by Django 3.0.4 on 2022-10-03 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0165_remove_fields_for_rebecca'),
        ('samples', '0163_sample_approved_negative_results'),
    ]

    operations = [
    ]
