# Generated by Django 3.0.4 on 2022-08-10 17:18

from django.db import migrations

def get_sample(extract):
	if extract.sample:
		return extract.sample
	elif extract.lysate:
		if extract.lysate.powder_sample:
			return extract.lysate.powder_sample.sample
	return None

def remove_fake_extracts(apps, queryset):
	Extract = apps.get_model('samples', 'Extract')
	Library = apps.get_model('samples', 'Library')
	ExtractionBatchLayout = apps.get_model('samples', 'ExtractionBatchLayout')
	LibraryBatchLayout = apps.get_model('samples', 'LibraryBatchLayout')
	for extract in Extract.objects.filter(extract_id__endswith='.NE'):
		# derived libraries are linked back to sample
		for library in Library.objects.filter(extract=extract):
			library.sample = get_sample(extract)
			library.extract = None
			library.save()
		# fake extracts should not be involved in extract plate layouts
		for extract_layout_element in ExtractionBatchLayout.objects.filter(extract=extract):
			extract_layout_element.delete()
		for library_layout_element in LibraryBatchLayout.objects.filter(extract=extract):
			library_layout_element.extract = None
			library_layout_element.save()
		extract.delete()

class Migration(migrations.Migration):

	dependencies = [
		('samples', '0165_remove_fields_for_rebecca'),
	]

	operations = [
		migrations.RunPython(remove_fake_extracts),
	]
