# Generated by Django 3.0.4 on 2022-10-20 22:59

from django.db import migrations

def switch(apps, queryset, start_state, end_state):
	LysateBatch = apps.get_model('samples', 'LysateBatch')
	
	for lysate_batch in LysateBatch.objects.filter(status=start_state):
		lysate_batch.status = end_state
		lysate_batch.save()

# lysates_created becomes closed
def lysates_created_to_closed(apps, queryset):
	switch(apps, queryset, 1, 200)
		
def closed_to_lysates_created(apps, queryset):
	switch(apps, queryset, 200, 1)


class Migration(migrations.Migration):

	dependencies = [
		('samples', '0166_merge_20221003_1031'),
	]

	operations = [
        migrations.RunPython(lysates_created_to_closed, closed_to_lysates_created),
	]
