# Generated by Django 3.0.4 on 2022-10-24 17:50

from django.db import migrations

def switch(apps, queryset, start_state, end_state):
	ExtractionBatch = apps.get_model('samples', 'ExtractionBatch')
	
	for extract_batch in ExtractionBatch.objects.filter(status=start_state):
		extract_batch.status = end_state
		extract_batch.save()

# extracted becomes closed
def extracted_to_closed(apps, queryset):
	switch(apps, queryset, 1, 200)
		
def closed_to_extracted(apps, queryset):
	switch(apps, queryset, 200, 1)


class Migration(migrations.Migration):

	dependencies = [
		('samples', '0167_lysate_batch_states'),
	]

	operations = [
		migrations.RunPython(extracted_to_closed, closed_to_extracted),
	]
