# Generated by Django 3.0.4 on 2022-10-25 14:37

from django.db import migrations

def switch(apps, queryset, start_state, end_state):
	LibraryBatch = apps.get_model('samples', 'LibraryBatch')
	
	for library_batch in LibraryBatch.objects.filter(status=start_state):
		library_batch.status = end_state
		library_batch.save()
		
# libraried becomes closed
def libraried_to_closed(apps, queryset):
	switch(apps, queryset, 1, 200)
		
def closed_to_libraried(apps, queryset):
	switch(apps, queryset, 200, 1)

class Migration(migrations.Migration):

	dependencies = [
		('samples', '0168_extract_batch_states'),
	]

	operations = [
		migrations.RunPython(libraried_to_closed, closed_to_libraried),
	]
