# Generated by Django 3.0.4 on 2022-10-14 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0166_merge_20221003_1031'),
        ('samples', '0169_lysatebatchlayout_lysate_fix'),
    ]

    operations = [
    ]
