# Generated by Django 3.0.4 on 2022-11-21 15:10

from django.db import migrations

def revalue_stop(apps, queryset, start_state, end_state):
	CaptureOrShotgunPlate = apps.get_model('samples', 'CaptureOrShotgunPlate')
	
	for batch in CaptureOrShotgunPlate.objects.filter(status=start_state):
		batch.status = end_state
		batch.save()
		
def forward(apps, queryset):
	revalue_stop(apps, queryset, -100, 1000)
		
def reverse(apps, queryset):
	revalue_stop(apps, queryset, 1000, -100)

class Migration(migrations.Migration):

	dependencies = [
		('samples', '0169_library_batch_states'),
	]

	operations = [
		migrations.RunPython(forward, reverse),
	]
