# Generated by Django 3.0.3 on 2023-03-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0170_capture_batch_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captureorshotgunplate',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Open'), (100, 'In Progress'), (200, 'Closed'), (1000, 'Stop')], default=0),
        ),
        migrations.AlterField(
            model_name='extractionbatch',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Open'), (100, 'In progress'), (200, 'Closed'), (1000, 'Stop')], default=0),
        ),
        migrations.AlterField(
            model_name='librarybatch',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Open'), (100, 'In progress'), (200, 'Closed'), (1000, 'Stop')], default=0),
        ),
        migrations.AlterField(
            model_name='lysatebatch',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Open'), (100, 'In progress'), (200, 'Closed'), (1000, 'Stop')], default=0),
        ),
    ]
