# Generated by Django 3.0.3 on 2023-03-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0171_auto_20230322_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='label',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
