# Generated by Django 3.0.3 on 2023-03-30 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

	dependencies = [
		('samples', '0172_barcode_label_length'),
	]

	operations = [
		migrations.SeparateDatabaseAndState(
			database_operations=[
					# switch from many-to-many to through model
					migrations.RunSQL(
						sql='ALTER TABLE samples_sequencingrun_indexed_libraries RENAME TO samples_sequencedlibrary',
						reverse_sql='ALTER TABLE samples_sequencedlibrary RENAME TO samples_sequencingrun_indexed_libraries',
					),
			],
			state_operations=[
				migrations.CreateModel(
					name='SequencedLibrary',
					fields=[
						('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
						('capturelayout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.CaptureLayout')),
						('sequencingrun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.SequencingRun')),
					],
				),
				migrations.AlterField(
					model_name='sequencingrun',
					name='indexed_libraries',
					field=models.ManyToManyField(through='samples.SequencedLibrary', to='samples.CaptureLayout'),
				),
			]
		)
	]
