# Generated by Django 3.0.3 on 2023-10-30 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0170_merge_20221014_1047'),
        ('samples', '0176_sample_approved_photo_sharing'),
    ]

    operations = [
    ]
