# Generated by Django 3.0.3 on 2023-11-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0177_merge_20231030_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='lysatebatch',
            name='freezer_date',
            field=models.DateField(null=True),
        ),
    ]
