# Generated by Django 3.0.3 on 2024-02-12 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0178_lysatebatch_freezer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionbatchlayout',
            name='powder_sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='samples.PowderSample'),
        ),
        migrations.AddField(
            model_name='extractionbatchlayout',
            name='powder_used_mg',
            field=models.FloatField(null=True),
        ),
    ]
