# Generated by Django 3.0.3 on 2024-05-02 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0179_auto_20240212_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='qpcr',
            new_name='qpcr_ds',
        ),
    ]
