# Generated by Django 3.0.3 on 2024-05-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0180_auto_20240502_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='assay_a_percent_inhibition',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='assay_b_total_molecules',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='qpcr_assay_a_1_ss',
            field=models.DecimalField(decimal_places=2, help_text='SS qpcr Assay A_1', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='qpcr_assay_a_2_ss',
            field=models.DecimalField(decimal_places=2, help_text='SS qpcr Assay A_2', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='qpcr_assay_b_1_ss',
            field=models.DecimalField(decimal_places=2, help_text='SS qpcr Assay B_1', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='qpcr_assay_b_2_ss',
            field=models.DecimalField(decimal_places=2, help_text='SS qpcr Assay B_2', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='qpcr_ds',
            field=models.DecimalField(decimal_places=2, help_text='DS qpcr value', max_digits=4, null=True),
        ),
    ]
