# Generated by Django 3.0.3 on 2024-05-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0181_auto_20240502_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarybatch',
            name='name',
            field=models.CharField(help_text='Usually ends with _DS or _SS', max_length=150, unique=True),
        ),
    ]
