# Generated by Django 3.0.3 on 2024-05-08 22:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0182_library_batch_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchaeologicalAssemblageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category for archaeological assemblage', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='For example, genetic or archaeological', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='sample',
            name='publications',
        ),
        migrations.AddField(
            model_name='culture',
            name='date_accuracy',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='date_end',
            field=models.IntegerField(help_text='Positive is year in CE. Negative is year BCE.', null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='date_start',
            field=models.IntegerField(help_text='Positive is year in CE. Negative is year BCE.', null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='super_culture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.Culture'),
        ),
        migrations.AddField(
            model_name='location',
            name='ecological_zone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='mountain',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='river_basin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='period',
            name='date_accuracy',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='period',
            name='date_end',
            field=models.IntegerField(help_text='Positive is year in CE. Negative is year BCE.', null=True),
        ),
        migrations.AddField(
            model_name='period',
            name='date_start',
            field=models.IntegerField(help_text='Positive is year in CE. Negative is year BCE.', null=True),
        ),
        migrations.AddField(
            model_name='radiocarbondatedsample',
            name='method',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sample',
            name='collection_keeper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collection_keeper', to='samples.Collaborator'),
        ),
        migrations.AddField(
            model_name='sample',
            name='excavator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='excavator', to='samples.Collaborator'),
        ),
        migrations.AlterField(
            model_name='radiocarbondatedsample',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.Sample'),
        ),
        migrations.CreateModel(
            name='SitePhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('modification_timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('date_start', models.IntegerField(help_text='Positive is year in CE. Negative is year BCE.', null=True)),
                ('date_end', models.IntegerField(help_text='Positive is year in CE. Negative is year BCE.', null=True)),
                ('date_accuracy', models.FloatField(null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='samples.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicationLabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('modification_timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20)),
                ('individual_id', models.CharField(help_text='Individual ID in paper', max_length=50)),
                ('group_label', models.CharField(blank=True, help_text='Group label for sample in paper', max_length=200)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='samples.Publication')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='samples.Sample')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArchaeologicalAssemblage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('modification_timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20)),
                ('burial_code', models.TextField()),
                ('date_start', models.IntegerField(help_text='Date from Archaeologist. Positive is year in CE. Negative is year BCE.', null=True)),
                ('date_end', models.IntegerField(help_text='Date from Archaeologist. Positive is year in CE. Negative is year BCE.', null=True)),
                ('date_notes', models.TextField(blank=True)),
                ('resolved_date_start', models.IntegerField(help_text='Positive is year in CE. Negative is year BCE.', null=True)),
                ('resolved_date_end', models.IntegerField(help_text='Positive is year in CE. Negative is year BCE.', null=True)),
                ('date_accuracy', models.FloatField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.ArchaeologicalAssemblageType')),
                ('site_phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.SitePhase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.PublicationType'),
        ),
        migrations.AddField(
            model_name='radiocarbondatedsample',
            name='archaeological_assemblage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.ArchaeologicalAssemblage'),
        ),
        migrations.AddField(
            model_name='sample',
            name='archaeological_assemblage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.ArchaeologicalAssemblage'),
        ),
    ]
