# Generated by Django 3.0.3 on 2024-05-03 21:33

from django.db import migrations

def do_nothing(apps, queryset):
	pass

def create_archaeological_assemblages_and_site_phases(apps, queryset):
	Location = apps.get_model('samples', 'Location')
	SitePhase = apps.get_model('samples', 'SitePhase')
	for location in Location.objects.all().order_by('pk'):
		SitePhase.objects.create(site=location)

	Sample = apps.get_model('samples', 'Sample')
	ArchaeologicalAssemblage = apps.get_model('samples', 'ArchaeologicalAssemblage')
	for sample in Sample.objects.all().order_by('pk'):
		if len(sample.control) == 0:
			site_phase = None
			if sample.location_fk is not None:
				site_phase = SitePhase.objects.get(site=sample.location_fk)

			sample.archaeological_assemblage = ArchaeologicalAssemblage.objects.create(site_phase=site_phase, burial_code=sample.burial_code)
			sample.save()


class Migration(migrations.Migration):

	dependencies = [
		('samples', '0183_leonid'),
	]

	operations = [
		migrations.RunPython(create_archaeological_assemblages_and_site_phases, do_nothing),
	]
