# Generated by Django 3.0.3 on 2024-05-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0184_arch_assemblage_site_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='publications',
            field=models.ManyToManyField(related_name='published_id_and_group_label', through='samples.PublicationLabels', to='samples.Publication'),
        ),
    ]
