# Generated by Django 3.0.3 on 2024-08-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0185_sample_publications_through'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captureorshotgunplate',
            name='needs_sequencing',
            field=models.BooleanField(default=True, help_text='True for new plates. False for plates sequenced before website switchover or if wells are manually assigned to sequencing runs.'),
        ),
    ]
