# Generated by Django 3.0.3 on 2024-05-09 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0185_sample_publications_through'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionbatchlayout',
            name='extract',
            field=models.OneToOneField(help_text='extract created in this well location', null=True, on_delete=django.db.models.deletion.SET_NULL, to='samples.Extract'),
        ),
        migrations.AlterField(
            model_name='librarybatchlayout',
            name='library',
            field=models.OneToOneField(help_text='library created from extract', null=True, on_delete=django.db.models.deletion.SET_NULL, to='samples.Library'),
        ),
        migrations.AlterField(
            model_name='lysatebatchlayout',
            name='lysate',
            field=models.OneToOneField(help_text='Lysate created in this well from powder', null=True, on_delete=django.db.models.deletion.SET_NULL, to='samples.Lysate'),
        ),
    ]
