# Generated by Django 3.0.3 on 2024-10-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0186_capture_needs_sequencing'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='special_restrictions',
            field=models.BooleanField(default=False, help_text='There are special restrictions on the use of this sample.', null=True),
        ),
    ]
