# Generated by Django 3.0.3 on 2024-10-30 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0187_sample_special_restrictions'),
        ('samples', '0186_one_to_one_layouts'),
    ]

    operations = [
    ]
