# Generated by Django 3.0.3 on 2024-11-18 21:39

from django.db import migrations

# As we switch powder used values from being stored in the PowderSample entry 
# to the LysateBatchLayout entry, for empty values
def copy_powder_used_to_lysate_layout(apps, queryset):
	PowderBatch = apps.get_model('samples', 'PowderBatch')
	PowderSample = apps.get_model('samples', 'PowderSample')
	LysateBatchLayout = apps.get_model('samples', 'LysateBatchLayout')
	
	for powder_batch in PowderBatch.objects.all():
		for powder_sample in PowderSample.objects.filter(powder_batch=powder_batch):
			try:
				layout_element = LysateBatchLayout.objects.get(powder_batch=powder_batch, powder_sample=powder_sample)
				if layout_element.powder_used_mg is None or layout_element.powder_used_mg == 0:
					layout_element.powder_used_mg = powder_sample.powder_for_extract
					layout_element.save()
			except LysateBatchLayout.DoesNotExist:
				pass # no object to store powder used, don't try to fix here

class Migration(migrations.Migration):

	dependencies = [
		('samples', '0188_merge_20241030_1750'),
	]

	operations = [
        migrations.RunPython(copy_powder_used_to_lysate_layout),
	]
