# Generated by Django 3.0.3 on 2024-12-04 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0189_powder_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powderprepqueue',
            name='prepared_powder',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samples.LysateBatchLayout'),
        ),
        migrations.AlterField(
            model_name='sampleprepqueue',
            name='prepared_powder',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samples.LysateBatchLayout'),
        ),
    ]
