# Generated by Django 3.0.3 on 2025-02-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0190_one_to_one_prepared_powder'),
    ]

    operations = [
        migrations.AddField(
            model_name='captureorshotgunplate',
            name='tip_batch',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
