# Generated by Django 3.0.3 on 2025-02-27 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0191_captureorshotgunplate_tip_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='qpcr_assay_a_2_ss',
        ),
        migrations.RemoveField(
            model_name='library',
            name='qpcr_assay_b_2_ss',
        ),
    ]
