# Generated by Django 3.0.3 on 2025-02-27 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0192_remove_qpcr_assay_x_2_ss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='qpcr_assay_a_1_ss',
            new_name='qpcr_assay_a_ss',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='qpcr_assay_b_1_ss',
            new_name='qpcr_assay_b_ss',
        ),
    ]
