# Generated by Django 3.0.3 on 2025-02-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0193_rename_qpcr_assay_x_1_ss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='qpcr_assay_a_ss',
            field=models.DecimalField(decimal_places=2, help_text='SS qpcr Assay A', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='qpcr_assay_b_ss',
            field=models.DecimalField(decimal_places=2, help_text='SS qpcr Assay B', max_digits=4, null=True),
        ),
    ]
