# Generated by Django 3.0.3 on 2025-02-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0194_assay_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarybatch',
            name='tip_batch',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
