# Generated by Django 3.0.3 on 2025-03-18 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0195_librarybatch_tip_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='archaeologicalassemblage',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.Location'),
        ),
    ]
