# Generated by Django 3.0.3 on 2025-03-18 01:56

from django.db import migrations

def copy_site(apps, schema_editor):
	ArchaeologicalAssemblage = apps.get_model('samples', 'ArchaeologicalAssemblage')
	any_failed = False
	for x in ArchaeologicalAssemblage.objects.all():
		if x.site_phase:
			x.site = x.site_phase.site
			x.save()

class Migration(migrations.Migration):

	dependencies = [
		('samples', '0196_archaeologicalassemblage_site'),
	]

	operations = [
		migrations.RunPython(copy_site),
	]
