# Generated by Django 3.0.3 on 2025-03-18 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0197_site_from_site_phase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archaeologicalassemblage',
            name='site_phase',
        ),
        migrations.DeleteModel(
            name='SitePhase',
        ),
    ]
