# Generated by Django 3.0.3 on 2025-03-18 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0198_remove_site_phase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='burial_code',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='locality',
        ),
    ]
