# Generated by Django 3.0.3 on 2025-03-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0199_remove_sample_burial_code_locality'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='group_label_use_country',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='group_label_use_culture',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='group_label_use_period',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='group_label_use_site',
            field=models.BooleanField(default=True),
        ),
    ]
