# Generated by Django 3.0.3 on 2025-03-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0200_group_label_use_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='burial_subcode',
            field=models.CharField(blank=True, help_text='For differentiating separate individuals in the same burial/archaeological assemblage', max_length=50),
        ),
    ]
