# Generated by Django 3.0.3 on 2025-03-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0201_sample_burial_subcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture',
            name='abbreviation',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='abbreviation',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
