# Generated by Django 3.0.3 on 2025-03-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0202_unique_period_culture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationlabels',
            name='individual_id',
            field=models.CharField(blank=True, help_text='Individual ID in paper', max_length=50),
        ),
    ]
