# Generated by Django 3.0.3 on 2025-03-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0203_blank_publication_ind_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='external_id',
            field=models.CharField(blank=True, help_text='identifier assigned externally', max_length=30, null=True, unique=True),
        ),
    ]
