# Generated by Django 3.0.3 on 2025-04-04 14:14

from django.db import migrations, models
import samples.validation


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0204_sample_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='abbreviation',
            field=models.CharField(help_text='Unique identifier for paper, no spaces allowed', max_length=50, null=True, unique=True, validators=[samples.validation.validate_no_whitespace]),
        ),
    ]
