# Generated by Django 3.0.3 on 2025-04-04 14:15

from django.db import migrations


def random_abbr(apps, queryset):
	Publication = apps.get_model('samples', 'Publication')
	for index, p in enumerate(Publication.objects.all()):
		p.abbreviation = str(index)
		p.save()

def do_nothing(apps, queryset):
	pass

class Migration(migrations.Migration):

	dependencies = [
		('samples', '0205_publication_abbreviation'),
	]

	operations = [
		migrations.RunPython(random_abbr, do_nothing)
	]
