# Generated by Django 3.0.3 on 2025-04-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0207_publication_abbreviation_nonnull'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='group_label_use_level_1',
            field=models.BooleanField(default=True),
        ),
    ]
