# Generated by Django 3.0.3 on 2025-04-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0208_sample_group_label_use_level_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='excavation_grid',
            field=models.TextField(blank=True, help_text='Sector unit and depth describing the particular part of the excavation area where this sample was found.'),
        ),
        migrations.AddField(
            model_name='sample',
            name='excavation_year',
            field=models.PositiveSmallIntegerField(help_text='The year this sample was excavated.', null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='skeletal_code',
            field=models.CharField(blank=True, help_text='Sample identification code assigned by the Reich Lab', max_length=150),
        ),
        migrations.AlterField(
            model_name='sample',
            name='skeletal_code_renamed',
            field=models.TextField(blank=True, help_text='Sample identification code assigned by the collaborator'),
        ),
    ]
