# Generated by Django 3.0.3 on 2025-04-14 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0209_sample_excavation_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='skeletal_code_renamed',
            new_name='collaborator_code',
        ),
    ]
