# Generated by Django 3.0.3 on 2025-04-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0210_collaborator_code_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='region',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='period',
            name='region',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sample',
            name='notes',
            field=models.TextField(blank=True, help_text='technician notes'),
        ),
    ]
