# Generated by Django 3.0.3 on 2025-04-21 23:51

from django.db import migrations

def site_from_sample(apps, queryset):
	Sample = apps.get_model('samples', 'Sample')
	
	for sample in Sample.objects.all():
		site1 = sample.location_fk
		try:
			site2 = sample.archaeological_assemblage.site
		except:
			site2 = None
		
		# location_fk is more reliable, if filled out
		if site1 is not None and site1 != site2:
			# create archaeological assemblage if there is not one
			if sample.archaeological_assemblage is None:
				sample.archaeological_assemblage = ArchaeologicalAssemblage()
				sample.save()
			sample.archaeological_assemblage.site = site1
			sample.archaeological_assemblage.save()
			
def site_from_archaeological_assemblage(apps, queryset):
	Sample = apps.get_model('samples', 'Sample')
	
	for sample in Sample.objects.all():
		site1 = sample.location_fk
		try:
			site2 = sample.archaeological_assemblage.site
		except:
			site2 = None
		
		# location_fk is more reliable, if filled out
		if site2 is not None and site1 != site2:
			sample.location_fk=site2
			sample.save()

class Migration(migrations.Migration):

	dependencies = [
		('samples', '0211_period_and_culture_region'),
	]

	operations = [
		migrations.RunPython(site_from_sample, site_from_archaeological_assemblage),
	]
