# Generated by Django 3.0.3 on 2025-04-22 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0212_site_resolution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='location_fk',
        ),
    ]
