# Generated by Django 3.0.3 on 2025-04-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0213_remove_sample_location_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationlabels',
            name='digital_accession_number',
            field=models.CharField(blank=True, help_text='Reference to access published data', max_length=100),
        ),
    ]
