# Generated by Django 3.0.3 on 2025-06-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0215_location_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationlabels',
            name='genetic_id',
            field=models.CharField(blank=True, help_text='Genetic ID identifying published analysis. Needed if there is more than one anno file line for this individual.', max_length=50),
        ),
    ]
