# Generated by Django 3.0.3 on 2025-06-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0216_publicationlabels_genetic_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='abbreviation',
            field=models.TextField(help_text='Unique identifier for paper', unique=True),
        ),
    ]
