# Generated by Django 3.0.3 on 2025-06-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0217_publication_abbr_allow_whitespace'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='date_stdev',
            field=models.DecimalField(decimal_places=1, max_digits=8, null=True),
        ),
    ]
