# Generated by Django 3.0.3 on 2025-06-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0218_sample_date_stdev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='group_label_use_level_1',
            field=models.BooleanField(default=False),
        ),
    ]
