# Generated by Django 3.0.3 on 2025-06-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0219_group_label_level1_default_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='date_end',
            field=models.IntegerField(help_text='Positive is year in CE. Negative is year BCE.', null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='date_start',
            field=models.IntegerField(help_text='Positive is year in CE. Negative is year BCE.', null=True),
        ),
    ]
