# Generated by Django 3.0.3 on 2025-08-01 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0221_genetic_analysis'),
        ('sequencing_run', '0020_genetic_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationlabels',
            name='genetic_id_entry',
            field=models.ForeignKey(help_text='Analysis that was published. This should replace the sample and text genetic ID.', null=True, on_delete=django.db.models.deletion.PROTECT, to='sequencing_run.GeneticAnalysis'),
        ),
        migrations.AlterField(
            model_name='assessmentcategory',
            name='category',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='publicationlabels',
            name='genetic_id',
            field=models.TextField(blank=True, help_text='Genetic ID identifying published analysis. Needed if there is more than one anno file line for this individual.'),
        ),
        migrations.DeleteModel(
            name='Instance',
        ),
        migrations.AddField(
            model_name='sequencingcomponents',
            name='data_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='samples.DataFile'),
        ),
        migrations.AddField(
            model_name='sequencingcomponents',
            name='sequenced_library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='samples.SequencedLibrary'),
        ),
        migrations.AddField(
            model_name='datainstance',
            name='data_files',
            field=models.ManyToManyField(through='samples.DataFileAssignment', to='samples.DataFile'),
        ),
        migrations.AddField(
            model_name='datainstance',
            name='primary_sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='samples.Sample'),
        ),
        migrations.AddField(
            model_name='datafileassignment',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.DataInstance'),
        ),
        migrations.AddField(
            model_name='datafileassignment',
            name='data_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.DataFile'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='file_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='samples.DataFileType'),
        ),
        migrations.AddField(
            model_name='sample',
            name='special_restriction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.SpecialRestriction'),
        ),
        migrations.AlterUniqueTogether(
            name='datafileassignment',
            unique_together={('data_file', 'collection', 'read_group')},
        ),
        migrations.AlterUniqueTogether(
            name='datafile',
            unique_together={('file_type', 'path')},
        ),
    ]
