# Generated by Django 3.0.3 on 2025-09-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0222_genetic_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='ancient_region',
            field=models.BooleanField(default=False, help_text='Ancient regions head the group label period section'),
        ),
    ]
