# Generated by Django 3.0.3 on 2025-09-22 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0223_period_ancient_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationlabels',
            name='published_data',
            field=models.ForeignKey(help_text='Published data. ', null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.DataInstance'),
        ),
    ]
