# Generated by Django 3.0.3 on 2025-09-22 16:56

from django.db import migrations
import sys

def to_genetic_id_fk(apps, schema_editor):
	PublicationLabels = apps.get_model('samples', 'PublicationLabels')
	GeneticAnalysis = apps.get_model('sequencing_run', 'GeneticAnalysis')
	DataInstance = apps.get_model('samples', 'DataInstance')
	
	failure = False
	for x in PublicationLabels.objects.all():
		# external data may have publication entry, but no corresponding GeneticAnalysis or DataInstance yet. 
		# only use manually set genetic_id
		if len(x.genetic_id) > 0:
			try:
				x.genetic_id_entry = GeneticAnalysis.objects.get(genetic_id=x.genetic_id)
				if x.published_data is not None and x.genetic_id_entry.data_instance != x.published_data:
					raise ValueError(f'Inconsistent data {str(x)} {x.genetic_id}')
				else:
					x.published_data = x.genetic_id_entry.data_instance
			except GeneticAnalysis.DoesNotExist:
				pass
		# Give up trying to correct all problems before migrating
		# if x.published_data is None:
		# 	print('No data for ' + str(x.id), file=sys.stderr)
		# 	failure = True
		x.save()
	if failure:
		raise ValueError()
		
def to_sample_and_genetic_id(apps, schema_editor):
	PublicationLabels = apps.get_model('samples', 'PublicationLabels')
	
	for x in PublicationLabels.objects.all():
		if x.genetic_id_entry is not None:
			x.genetic_id = x.genetic_id_entry.genetic_id
			x.sample = x.genetic_id_entry.data_instance.primary_sample
		else:
			x.sample = x.data_instance.primary_sample
		x.save()

class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0224_publication_data_instance'),
    ]

    operations = [
		migrations.RunPython(to_genetic_id_fk, to_sample_and_genetic_id)
    ]
