# Generated by Django 3.0.3 on 2025-10-22 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0225_genetic_id_publications'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='primary_sample',
            field=models.ForeignKey(help_text='Primary sample entry for data. Use for duplicates.', null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.Sample'),
        ),
    ]
