# Generated by Django 3.0.3 on 2025-10-22 19:39

from django.db import migrations

import re
import sys
from collections import Counter

SID_IID_REGEX = re.compile(r'[SI]?(?P<sample>\d{4,})')

# use the individual ID text field to infer new primary sample field
def fill_primary_sample(apps, schema_editor):
	Sample = apps.get_model('samples', 'Sample')
	# dictionary of individual ids with counts
	individual_ids = Counter()
	for sample in Sample.objects.exclude(individual_id='').filter(control='').values('individual_id').order_by('individual_id', 'id'):
		individual_ids[sample['individual_id']] += 1
	
	for individual_id in individual_ids:
		if individual_ids[individual_id] > 1:
			individual_set = Sample.objects.filter(individual_id=individual_id)
			primary_sample = None
			# Does this look like a Reich Lab ID?
			match = re.fullmatch(SID_IID_REGEX, individual_id)
			if match is not None:
				try:
					primary_sample = individual_set.get(reich_lab_id=int(match.group('sample')), control='')
				except Sample.DoesNotExist:
					pass
				except Sample.MultipleObjectsReturned as e:
					print(individual_id)
					raise e
			if primary_sample is None:
				try:
					primary_sample = individual_set.get(external_id=individual_id)
				except Sample.DoesNotExist:
					pass
			if primary_sample is None:
				primary_sample = individual_set.first()
			to_update = individual_set.exclude(id=primary_sample.id)
			for sample in to_update:
				sample.primary_sample = primary_sample
				sample.save()
			
def do_nothing(apps, schema_editor):
	pass

class Migration(migrations.Migration):

	dependencies = [
		('samples', '0226_sample_primary_sample'),
	]

	operations = [
		migrations.RunPython(fill_primary_sample, do_nothing)
	]
