# Generated by Django 3.0.3 on 2025-10-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0227_fill_primary_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
