# Generated by Django 3.0.3 on 2025-10-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0228_publication_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='group_label_use_level_2',
            field=models.BooleanField(default=False),
        ),
    ]
