# Generated by Django 3.0.3 on 2025-11-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0229_sample_group_label_use_level_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='secondary_collaborators',
            field=models.ManyToManyField(related_name='secondary_collaborators', to='samples.Collaborator'),
        ),
    ]
