# Generated by Django 3.0.3 on 2025-11-03 16:20

from django.db import migrations

import sys

def get_collaborator(part, Collaborator):
	last_name, first_name = [s.strip() for s in part.split(',')]
	collaborator = Collaborator.objects.get(last_name=last_name, first_name=first_name)
	return collaborator

def fill_secondary_collaborators(apps, schema_editor):
	Sample = apps.get_model('samples', 'Sample')
	Collaborator = apps.get_model('samples', 'Collaborator')
	for sample in Sample.objects.all():
		if len(sample.collaborators) > 0:
			try:
				parts = sample.collaborators.split(';')
				# if any part is not recognizable as a collaborator's [last name], [first name]
				# print an error and skip this sample
				collaborators = [get_collaborator(part, Collaborator) for part in parts]
				for collaborator in collaborators:
					sample.secondary_collaborators.add(collaborator)
					
			except (Collaborator.DoesNotExist, Collaborator.MultipleObjectsReturned, ValueError) as e:
				print(f'{sample.id}\t{sample.collaborators}', file=sys.stderr)

def collaborators_text_field(apps, schema_editor):
	Sample = apps.get_model('samples', 'Sample')
	for sample in Sample.objects.all():
		if len(sample.secondary_collaborators) > 0:
			sample.collaborators = '; '.join([f'{c.last_name}, {c.first_name}' for c in sample.secondary_collaborators])
			sample.save()

class Migration(migrations.Migration):

	dependencies = [
		('samples', '0230_sample_secondary_collaborators'),
	]

	operations = [
		migrations.RunPython(fill_secondary_collaborators, collaborators_text_field)
	]
