# Generated by Django 3.0.3 on 2025-12-15 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0231_fill_secondary_collaborators'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafileassignment',
            name='created_by',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='datafileassignment',
            name='creation_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='datafileassignment',
            name='modification_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='datafileassignment',
            name='modified_by',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
