# Generated by Django 3.0.3 on 2025-12-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0232_DataFileAssignment_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lysate',
            name='barcode',
            field=models.CharField(blank=True, help_text='Physical barcode on FluidX tube', max_length=12, null=True),
        ),
    ]
