# Generated by Django 3.0.3 on 2025-12-18 15:17

from django.db import migrations
from django.utils import timezone

def to_null(apps, schema_editor):
	Lysate = apps.get_model('samples', 'Lysate')
	lysates_to_change = Lysate.objects.filter(barcode='')
	modification_time = timezone.now()
	for lysate in lysates_to_change:
		lysate.barcode = None
		lysate.modification_timestamp = modification_time
		lysate.modified_by = 'migration'
		lysate.save()
	
def to_blank(apps, schema_editor):
	Lysate = apps.get_model('samples', 'Lysate')
	lysates_to_change = Lysate.objects.filter(barcode__isnull=True)
	modification_time = timezone.now()
	for lysate in lysates_to_change:
		lysate.barcode = ''
		lysate.modification_timestamp = modification_time
		lysate.modified_by = 'migration'
		lysate.save()

class Migration(migrations.Migration):

	dependencies = [
		('samples', '0233_lysate_barcode_null'),
	]

	operations = [
		migrations.RunPython(to_null, to_blank)
	]
