# Generated by Django 3.0.3 on 2025-12-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0234_lysate_fluidx_barcode_to_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lysate',
            name='barcode',
            field=models.CharField(help_text='Physical barcode on FluidX tube', max_length=12, null=True, unique=True),
        ),
    ]
