# Generated by Django 3.0.3 on 2025-12-18 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0235_unique_possibly_null_lysate_fluidx_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='culture',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='period',
        ),
    ]
