# Generated by Django 3.0.3 on 2025-12-22 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0236_sample_remove_culture_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationLevelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('is_suffix', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='level_1_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='samples.LocationLevelType'),
        ),
        migrations.AddField(
            model_name='location',
            name='level_2_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='samples.LocationLevelType'),
        ),
        migrations.AddField(
            model_name='location',
            name='level_3_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='samples.LocationLevelType'),
        ),
        migrations.AddField(
            model_name='location',
            name='level_4_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='samples.LocationLevelType'),
        ),
        migrations.AddField(
            model_name='location',
            name='level_5_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='samples.LocationLevelType'),
        ),
    ]
