# Generated by Django 3.0.3 on 2025-12-22 16:12

from django.db import migrations
from django.utils import timezone

move_strings = [
	'Province',
	'Municipality',
	'Oblast',
	'District',
	'State',
	'Region',
	'Village',
	'Republic of',
	'Republic',
	'Islands',
	'Island',
	'Sub-Region',
	'Mouth of the',
	'Autonomous Okrug',
	'modern',
	'County',
	'Governorate',
	'Prefecture',
	'Town',
	'Dpto.',
	'City',
	'Autonomous',
	'Stadt',
	'Department',
	'Arrondissement',
]

fields = [f'level_{n}' for n in range(1, 6)]

def clean_level_of_type(apps, location, field):
	current = getattr(location, field)
	initial = current
	for s in move_strings:
		if current:
			current = current.removeprefix(s).removeprefix(s.lower()).removesuffix(s).removesuffix(s.lower())
		# only expect up to one location type
		if current != initial:
			setattr(location, field, current.strip())
			LocationLevelType = apps.get_model('samples', 'LocationLevelType')
			location_level_type, created = LocationLevelType.objects.get_or_create(name=s)
			setattr(location, field + '_type', location_level_type)
			return True
	return False
	

def location_level_types(apps, schema_editor):
	Location = apps.get_model('samples', 'Location')
	for location in Location.objects.all():
		modified = False
		for field in fields:
			modified = clean_level_of_type(apps, location, field) or modified
		if modified:
			location.modification_timestamp = timezone.now()
			location.modified_by = 'migration'
			location.save()
				
def do_nothing(apps, schema_editor):
	pass

class Migration(migrations.Migration):

	dependencies = [
		('samples', '0237_location_level_types'),
	]

	operations = [
		migrations.RunPython(location_level_types, do_nothing)
	]
