# Generated by Django 3.0.3 on 2025-12-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0238_location_level_type_move'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='is_institution',
            field=models.BooleanField(default=False, help_text='Is an institution and not a person'),
        ),
    ]
