# Generated by Django 3.0.3 on 2026-01-05 19:59

from django.db import migrations
from django.db.models import Q
from django.utils import timezone

def trim_spaces_lysate(apps, schema_editor):
	Lysate = apps.get_model('samples', 'Lysate')
	lysates = Lysate.objects.filter(Q(barcode__startswith=' ') | Q(barcode__endswith=' '))
	modified_time = timezone.now()
	for lysate in lysates:
		lysate.barcode = lysate.barcode.strip()
		lysate.modified_by = 'migration'
		lysate.modification_timestamp = modified_time
		lysate.save()
		
def trim_spaces_library(apps, schema_editor):
	Library = apps.get_model('samples', 'Library')
	libraries = Library.objects.filter(Q(fluidx_barcode__startswith=' ') | Q(fluidx_barcode__endswith=' '))
	modified_time = timezone.now()
	for library in libraries:
		library.fluidx_barcode = library.fluidx_barcode.strip()
		library.modified_by = 'migration'
		library.modification_timestamp = modified_time
		library.save()
		
	
def do_nothing(apps, schema_editor):
	pass

class Migration(migrations.Migration):

	dependencies = [
		('samples', '0239_collaborator_is_institution'),
	]

	operations = [
		migrations.RunPython(trim_spaces_lysate, do_nothing),
		migrations.RunPython(trim_spaces_library, do_nothing),
	]
