# Generated by Django 3.0.3 on 2026-01-27 14:31

from django.db import migrations
from django.utils import timezone

def empty_to_null(apps, schema_editor):
	Library = apps.get_model('samples', 'Library')
	libraries = Library.objects.filter(fluidx_barcode='')
	modified_time = timezone.now()
	for library in libraries:
		library.fluidx_barcode = None
		library.modified_by = 'migration'
		library.modification_timestamp = modified_time
		library.save()
	
def do_nothing(apps, schema_editor):
	pass

class Migration(migrations.Migration):

	dependencies = [
		('samples', '0241_validate_fluidx_nospaces'),
	]

	operations = [
		migrations.RunPython(empty_to_null, do_nothing),
	]
