# Generated by Django 3.0.3 on 2026-01-27 14:31

from django.db import migrations, models
import samples.validation


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0242_library_fluidx_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='fluidx_barcode',
            field=models.CharField(help_text='Physical barcode on FluidX tube', max_length=12, null=True, unique=True, validators=[samples.validation.validate_no_whitespace]),
        ),
    ]
