# Generated by Django 3.0.3 on 2026-02-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0243_library_fluidx_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationlabels',
            name='meta_data_published',
            field=models.BooleanField(default=True, help_text='Generally samples have meta data published with data. However, there are examples of samples having genetic data published without their metadata, usually with the intention that the metadata will be appear in a later publication.'),
        ),
    ]
