# Generated by Django 3.0.3 on 2026-02-26 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0244_publicationlabels_meta_data_published'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('site', 'country')},
        ),
    ]
