# Generated by Django 3.0.3 on 2026-03-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0245_unique_site_name_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Drafts do not mark genetic analysis entries as published. This should be false for any published paper. '),
        ),
    ]
