# Generated by Django 3.0.3 on 2026-03-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0246_publication_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='identifier assigned externally', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='individual_id',
            field=models.CharField(blank=True, db_index=True, max_length=15),
        ),
    ]
